# Generated by Django 3.2.12 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonofficialtitle',
            name='non_official_journal_title',
            field=models.TextField(verbose_name='Non Official Journal Title'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='nlm_title',
            field=models.TextField(blank=True, null=True, verbose_name='NLM Title'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='short_title',
            field=models.TextField(blank=True, null=True, verbose_name='Short Title'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Official Title'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='title_iso',
            field=models.TextField(blank=True, null=True, verbose_name='Title ISO'),
        ),
    ]
