# Generated by Django 3.2.12 on 2022-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_title_i_377c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_nlm_tit_c1aab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_foundat_adccd1_idx',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='nlm_title',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='title_iso',
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Day'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Month'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Year'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='short_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ISO Short Title'),
        ),
        migrations.AddIndex(
            model_name='officialjournal',
            index=models.Index(fields=['foundation_year'], name='journal_off_foundat_fcc7eb_idx'),
        ),
    ]
