# Generated by Django 3.2.12 on 2022-08-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonOfficialJournalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nonofficialjournaltitle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameModel(
            old_name='NonOfficialTitles',
            new_name='NonOfficialTitle',
        ),
        migrations.DeleteModel(
            name='NonOfficialJournalTitles',
        ),
        migrations.AddField(
            model_name='nonofficialjournaltitle',
            name='official_journal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfficialJournal', to='journal.officialjournal'),
        ),
        migrations.AddField(
            model_name='nonofficialjournaltitle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonofficialjournaltitle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='nonofficialtitle',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_non_official_title', to='journal.nonofficialjournaltitle'),
        ),
    ]
