# Generated by Django 4.2.6 on 2024-03-11 11:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="page",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="page",
        ),
        migrations.AddField(
            model_name="journal",
            name="title",
            field=models.CharField(
                blank=True, max_length=265, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publisher",
                to="journal.journal",
            ),
        ),
    ]
