# Generated by Django 3.2.12 on 2022-08-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20220823_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonofficialjournaltitle',
            old_name='official_journal_id',
            new_name='official_journal',
        ),
    ]
