# Generated by Django 4.2.6 on 2024-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_remove_owner_page_remove_publisher_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="journal_acron",
            field=models.TextField(
                blank=True, null=True, verbose_name="Journal Acronym"
            ),
        ),
    ]
