# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20230709_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_auto_20230303_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciELOJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('scielo_issn', models.CharField(max_length=9, verbose_name='SciELO ISSN')),
                ('acron', models.CharField(blank=True, max_length=25, null=True, verbose_name='Acronym')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('availability_status', models.CharField(blank=True, choices=[('?', 'Unknown'), ('C', 'Current')], max_length=10, null=True, verbose_name='Availability Status')),
            ],
        ),
        migrations.AlterModelOptions(
            name='officialjournal',
            options={'verbose_name': 'Official Journal', 'verbose_name_plural': 'Official Journals'},
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_title_2bbaa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_title_i_377c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_short_t_83fcd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_nlm_tit_c1aab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_foundat_adccd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_ISSN_pr_8d870f_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_ISSN_el_cb6923_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_ISSNL_b0b8f7_idx',
        ),
        migrations.RenameField(
            model_name='officialjournal',
            old_name='ISSN_print',
            new_name='issn_print',
        ),
        migrations.RenameField(
            model_name='officialjournal',
            old_name='ISSNL',
            new_name='issnl',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='ISSN_electronic',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='foundation_date',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='nlm_title',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='short_title',
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Foundation Year'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='issn_electronic',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ISSN Eletronic'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='title_iso',
            field=models.TextField(blank=True, null=True, verbose_name='ISO Title'),
        ),
        migrations.AddIndex(
            model_name='officialjournal',
            index=models.Index(fields=['issn_print'], name='journal_off_issn_pr_dccb39_idx'),
        ),
        migrations.AddIndex(
            model_name='officialjournal',
            index=models.Index(fields=['issn_electronic'], name='journal_off_issn_el_89169a_idx'),
        ),
        migrations.AddIndex(
            model_name='officialjournal',
            index=models.Index(fields=['issnl'], name='journal_off_issnl_4304c5_idx'),
        ),
        migrations.AddField(
            model_name='scielojournal',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='scielojournal',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scielojournal_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='scielojournal',
            name='official_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.officialjournal'),
        ),
        migrations.AddField(
            model_name='scielojournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scielojournal_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddIndex(
            model_name='scielojournal',
            index=models.Index(fields=['acron'], name='journal_sci_acron_6691c1_idx'),
        ),
        migrations.AddIndex(
            model_name='scielojournal',
            index=models.Index(fields=['collection'], name='journal_sci_collect_f6fb08_idx'),
        ),
        migrations.AddIndex(
            model_name='scielojournal',
            index=models.Index(fields=['scielo_issn'], name='journal_sci_scielo__adf1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='scielojournal',
            index=models.Index(fields=['availability_status'], name='journal_sci_availab_da835a_idx'),
        ),
        migrations.AddIndex(
            model_name='scielojournal',
            index=models.Index(fields=['official_journal'], name='journal_sci_officia_c9deda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scielojournal',
            unique_together={('collection', 'acron'), ('collection', 'scielo_issn')},
        ),
    ]
