# Generated by Django 3.2.12 on 2022-09-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_official_journal_id_nonofficialjournaltitle_official_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonofficialjournaltitle',
            name='official_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OfficialJournal', to='journal.officialjournal'),
        ),
    ]
