# Generated by Django 5.0.3 on 2024-08-19 20:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
        ("journal", "0004_remove_journal_journal_acron_journal_acron_and_more"),
        ("location", "0002_alter_country_acronym_alter_state_acronym_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="contact_address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="journal",
            name="contact_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="contact_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="mission",
            unique_together={("journal", "language")},
        ),
        migrations.CreateModel(
            name="JournalEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_email",
                        to="journal.journal",
                    ),
                ),
            ],
            options={
                "unique_together": {("journal", "email")},
            },
        ),
    ]
