# Generated by Django 5.0.3 on 2024-10-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_journal_contact_address_journal_contact_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialjournal",
            name="next_journal_title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="officialjournal",
            name="previous_journal_title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_acron",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Journal Acronym"
            ),
        ),
    ]
