# Generated by Django 5.0.3 on 2024-11-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_officialjournal_next_journal_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalsection",
            name="text",
            field=models.CharField(max_length=200),
        ),
    ]
