# Generated by Django 5.0.3 on 2025-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_alter_journalsection_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="wos_areas",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
