# Generated by Django 5.0.3 on 2024-11-13 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_journaltoc_alter_journal_official_journal_and_more"),
        ("journal", "0006_alter_journalsection_text"),
    ]

    operations = []
