# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_journal_wos_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="nlm_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Official Title"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title_iso",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ISO Title"
            ),
        ),
    ]
