# Generated by Django 5.0.3 on 2025-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_alter_journal_contact_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialjournal",
            name="previous_journal_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
