# Generated by Django 5.0.3 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0009_alter_officialjournal_previous_journal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Address"
            ),
        ),
    ]
