# Generated by Django 5.0.3 on 2025-06-20 16:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0010_alter_journal_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="official_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.officialjournal",
            ),
        ),
        migrations.AlterField(
            model_name="journalsection",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="journalsection",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="j_sections",
                to="journal.journal",
            ),
        ),
    ]
