# Generated by Django 5.0.3 on 2025-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0010_alter_journal_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
