# Generated by Django 5.0.8 on 2025-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("journal", "0012_journal_core_synchronized"),
        ("journal", "0013_alter_subject_code"),
    ]

    dependencies = [
        ("journal", "0011_alter_journal_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="core_synchronized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
