# Generated by Django 5.0.8 on 2025-06-26 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_merge_0007_journal_wos_areas_0007_merge_20241113_1945"),
        ("journal", "0011_alter_journal_contact_address_and_more"),
    ]

    operations = []
