# Generated by Django 5.0.8 on 2025-06-27 03:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_merge_20250626_1842"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JournalTOC",
        ),
        migrations.AlterField(
            model_name="journalsection",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="j_sections",
                to="journal.journal",
            ),
        ),
    ]
