# Generated by Django 5.0.3 on 2025-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_journaltoc_alter_journal_official_journal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="journalsection",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
