# Generated by Django 5.0.3 on 2025-06-03 22:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("journal", "0014_alter_journalsection_parent"),
        ("journal", "0015_alter_journalsection_parent"),
        ("journal", "0016_delete_journaltoc"),
        ("journal", "0017_alter_journalsection_parent"),
        ("journal", "0018_alter_journalsection_parent"),
    ]

    dependencies = [
        ("journal", "0013_alter_journal_contact_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalsection",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="j_sections",
                to="journal.journal",
            ),
        ),
        migrations.DeleteModel(
            name="JournalTOC",
        ),
    ]
