# Generated by Django 5.2.3 on 2025-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_journal_core_synchronized_squashed_0013_alter_subject_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Official Title"
            ),
        ),
    ]
