# Generated by Django 5.0.8 on 2025-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0013_delete_journaltoc_alter_journalsection_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="core_synchronized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
