# Generated by Django 5.2.3 on 2026-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_alter_journal_title_alter_officialjournal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialjournal",
            name="next_journal_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
