# Generated by Django 5.2.3 on 2026-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0015_alter_officialjournal_next_journal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
