# Generated by Django 4.1.10 on 2023-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files_storage", "0001_initial"),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PkgAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("comment", "comment"),
                            ("package-error", "package error"),
                            ("warning", "warning"),
                            ("execution-failure", "execution failure"),
                        ],
                        default="comment",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("annotation_subtype", models.TextField(blank=True, null=True)),
                ("annotation_text", models.TextField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SPSComponent",
            fields=[
                (
                    "filelocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="files_storage.filelocation",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Package component type",
                    ),
                ),
                ("xml_elem_id", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "lang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.language",
                    ),
                ),
            ],
            bases=("files_storage.filelocation",),
        ),
        migrations.CreateModel(
            name="SPSPkg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("pid_v3", models.CharField(blank=True, max_length=23, null=True)),
                (
                    "sps_pkg_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="SPS Name"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=package.models.pkg_directory_path,
                    ),
                ),
                ("xml_uri", models.URLField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIGRATION", "MIGRATION"),
                            ("INGRESS_WITH_VALIDATION", "INGRESS_WITH_VALIDATION"),
                            (
                                "INGRESS_WITHOUT_VALIDATION",
                                "INGRESS_WITHOUT_VALIDATION",
                            ),
                        ],
                        default="INGRESS_WITHOUT_VALIDATION",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(blank=True, null=True)),
                ("annotations", models.ManyToManyField(to="package.pkgannotation")),
                ("components", models.ManyToManyField(to="package.spscomponent")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pkgannotation",
            name="sps_pkg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="package.spspkg",
            ),
        ),
        migrations.AddField(
            model_name="pkgannotation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(fields=["pid_v3"], name="package_sps_pid_v3_74c613_idx"),
        ),
        migrations.AddIndex(
            model_name="spscomponent",
            index=models.Index(fields=["lang"], name="package_sps_lang_id_ef40c5_idx"),
        ),
        migrations.AddIndex(
            model_name="spscomponent",
            index=models.Index(
                fields=["category"], name="package_sps_categor_ab284b_idx"
            ),
        ),
    ]
