# Generated by Django 4.2.6 on 2023-12-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files_storage", "0001_initial"),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SPSPkg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("pid_v3", models.CharField(blank=True, max_length=23, null=True)),
                (
                    "sps_pkg_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="SPS Name"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=package.models.pkg_directory_path,
                    ),
                ),
                ("xml_uri", models.URLField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIGRATION", "MIGRATION"),
                            ("INGRESS_WITH_VALIDATION", "INGRESS_WITH_VALIDATION"),
                            (
                                "INGRESS_WITHOUT_VALIDATION",
                                "INGRESS_WITHOUT_VALIDATION",
                            ),
                        ],
                        default="INGRESS_WITHOUT_VALIDATION",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("scheduled", models.DateTimeField(blank=True, null=True)),
                (
                    "is_pid_provider_synchronized",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "storaged_files_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expected_components_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("valid_components", models.BooleanField(blank=True, null=True)),
                ("texts", models.JSONField(blank=True, null=True)),
                ("valid_texts", models.BooleanField(blank=True, null=True)),
                ("is_public", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SPSPkgComponent",
            fields=[
                (
                    "filelocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="files_storage.filelocation",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "component_type",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Package component type",
                    ),
                ),
                ("xml_elem_id", models.CharField(blank=True, max_length=8, null=True)),
                ("legacy_uri", models.TextField(blank=True, null=True)),
                (
                    "lang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.language",
                    ),
                ),
                (
                    "sps_pkg",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component",
                        to="package.spspkg",
                    ),
                ),
            ],
            bases=("files_storage.filelocation", models.Model),
        ),
        migrations.AddField(
            model_name="spspkg",
            name="components",
            field=models.ManyToManyField(to="package.spspkgcomponent"),
        ),
        migrations.AddField(
            model_name="spspkg",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="spspkg",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.CreateModel(
            name="PreviewArticlePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=package.models.pkg_directory_path,
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.language",
                    ),
                ),
                (
                    "sps_pkg",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_page",
                        to="package.spspkg",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="spspkgcomponent",
            index=models.Index(fields=["lang"], name="package_sps_lang_id_06dbb6_idx"),
        ),
        migrations.AddIndex(
            model_name="spspkgcomponent",
            index=models.Index(
                fields=["component_type"], name="package_sps_compone_25ebb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(fields=["pid_v3"], name="package_sps_pid_v3_74c613_idx"),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(
                fields=["sps_pkg_name"], name="package_sps_sps_pkg_0d3fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(
                fields=["valid_texts"], name="package_sps_valid_t_571466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(
                fields=["valid_components"], name="package_sps_valid_c_37274c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spspkg",
            index=models.Index(
                fields=["is_pid_provider_synchronized"],
                name="package_sps_is_pid__34a0cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="previewarticlepage",
            index=models.Index(fields=["lang"], name="package_pre_lang_id_21cb28_idx"),
        ),
    ]
