# Generated by Django 5.0.3 on 2024-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0003_remove_spspkg_components_remove_spspkg_scheduled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spspkg",
            name="sps_pkg_name",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="SPS Name"
            ),
        ),
    ]
