# Generated by Django 5.0.3 on 2025-02-24 18:21

import package.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0004_alter_spspkg_sps_pkg_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spspkg",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=150,
                null=True,
                upload_to=package.models.pkg_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="spspkg",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("MIGRATION", "MIGRATION"), ("UPLOAD", "UPLOAD")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spspkg",
            name="sps_pkg_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="SPS Name"
            ),
        ),
        migrations.AlterField(
            model_name="spspkgcomponent",
            name="legacy_uri",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
