# Generated by Django 5.0.3 on 2025-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0005_alter_spspkg_file_alter_spspkg_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spspkg",
            name="sps_pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="SPS Name"
            ),
        ),
    ]
