# Generated by Django 5.2.3 on 2025-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0006_alter_spspkg_sps_pkg_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreviewArticlePage",
        ),
    ]
