# Generated by Django 5.2.3 on 2026-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0007_delete_previewarticlepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="spspkg",
            name="pid_v2",
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
