# Generated by Django 5.2.3 on 2026-08-14 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0008_spspkg_pid_v2"),
        ("pid_provider", "0015_pidprovidersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="spspkg",
            name="ppx",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pid_provider.pidproviderxml",
            ),
        ),
    ]
