# Generated by Django 5.0.3 on 2024-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Country Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="State Acronym"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name", "acronym")},
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("name", "acronym")},
        ),
    ]
