# Generated by Django 5.2.3 on 2025-09-29 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_alter_country_acronym_alter_state_acronym_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
    ]
