# Generated by Django 3.2.12 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedat',
            name='acronym',
            field=models.TextField(null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='indexedat',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='indexedat',
            name='name',
            field=models.TextField(null=True, verbose_name='Nome'),
        ),
    ]
