# Generated by Django 4.2.6 on 2023-12-11 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import htmlxml.models
import modelcluster.fields
import package.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyAndBackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=htmlxml.models.body_and_back_directory_path,
                    ),
                ),
                ("version", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Html2xmlAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("empty_body", models.BooleanField(blank=True, null=True)),
                (
                    "attention_demands",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "html_img_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "html_table_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_supplmat_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_media_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_fig_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_table_wrap_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("xml_eq_total", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "xml_graphic_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_inline_graphic_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_ref_elem_citation_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_ref_mixed_citation_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xml_text_lang_total",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "article_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HTMLXML",
            fields=[
                (
                    "html2xmlanalysis_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="htmlxml.html2xmlanalysis",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=package.models.basic_xml_directory_path,
                    ),
                ),
                (
                    "html2xml_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVED", "approved automatically"),
                            ("APPROVED", "approved"),
                            ("REJECTED", "rejected"),
                            ("NOT_EVALUATED", "not evaluated"),
                        ],
                        default="NOT_EVALUATED",
                        max_length=16,
                        verbose_name="Quality",
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=htmlxml.models.generated_xml_report_directory_path,
                    ),
                ),
                ("n_paragraphs", models.IntegerField(default=0)),
                ("n_references", models.IntegerField(default=0)),
                (
                    "record_types",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "html_translation_langs",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
            ],
            bases=("htmlxml.html2xmlanalysis", models.Model),
        ),
        migrations.AddIndex(
            model_name="html2xmlanalysis",
            index=models.Index(
                fields=["attention_demands"], name="htmlxml_htm_attenti_3769ed_idx"
            ),
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="article_proc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proc.articleproc",
            ),
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="bodyandbackfile",
            name="bb_parent",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bb_file",
                to="htmlxml.htmlxml",
            ),
        ),
        migrations.AddIndex(
            model_name="htmlxml",
            index=models.Index(
                fields=["html2xml_status"], name="htmlxml_htm_html2xm_fb63cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="htmlxml",
            index=models.Index(
                fields=["quality"], name="htmlxml_htm_quality_fdc38a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="htmlxml",
            index=models.Index(
                fields=["article_proc"], name="htmlxml_htm_article_641634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bodyandbackfile",
            index=models.Index(
                fields=["version"], name="htmlxml_bod_version_9acdda_idx"
            ),
        ),
    ]
