# Generated by Django 5.0.3 on 2024-03-29 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("htmlxml", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="htmlxml",
            options={"ordering": ["-updated"]},
        ),
    ]
