# Generated by Django 4.2.6 on 2024-01-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0002_alter_migrateddata_migration_status"),
        ("htmlxml", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="htmlxml",
            name="htmlxml_htm_article_641634_idx",
        ),
        migrations.RemoveField(
            model_name="htmlxml",
            name="article_proc",
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="migrated_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="migration.migratedarticle",
            ),
        ),
        migrations.AlterField(
            model_name="htmlxml",
            name="html2xml_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="htmlxml",
            index=models.Index(
                fields=["migrated_article"], name="htmlxml_htm_migrate_c9013f_idx"
            ),
        ),
    ]
