# Generated by Django 5.2.3 on 2026-01-15 12:47

import htmlxml.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("htmlxml", "0002_alter_htmlxml_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlxml",
            name="bb_init_file",
            field=models.FileField(
                blank=True,
                help_text="Initial HTML structured in body, back, ref-list",
                null=True,
                upload_to=htmlxml.models.body_and_back_directory_path,
                verbose_name="Initial HTML file",
            ),
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="conversion_steps_zip_file",
            field=models.FileField(
                blank=True,
                help_text="ZIP file containing all body and back XML versions",
                null=True,
                upload_to=htmlxml.models.body_and_back_directory_path,
                verbose_name="Body and Back ZIP file",
            ),
        ),
    ]
