# Generated by Django 5.2.3 on 2026-02-11 18:16

import htmlxml.models
import package.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("htmlxml", "0003_htmlxml_bb_init_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyandbackfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=htmlxml.models.body_and_back_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="htmlxml",
            name="bb_init_file",
            field=models.FileField(
                blank=True,
                help_text="Initial HTML structured in body, back, ref-list",
                max_length=300,
                null=True,
                upload_to=htmlxml.models.body_and_back_directory_path,
                verbose_name="Initial HTML file",
            ),
        ),
        migrations.AlterField(
            model_name="htmlxml",
            name="conversion_steps_zip_file",
            field=models.FileField(
                blank=True,
                help_text="ZIP file containing all body and back XML versions",
                max_length=300,
                null=True,
                upload_to=htmlxml.models.body_and_back_directory_path,
                verbose_name="Body and Back ZIP file",
            ),
        ),
        migrations.AlterField(
            model_name="htmlxml",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=package.models.basic_xml_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="htmlxml",
            name="report",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=htmlxml.models.generated_xml_report_directory_path,
            ),
        ),
    ]
