x-django-function: &django-function
  image: infrascielo/upload:${SCMS_WEBAPP_VERSION}
  restart: unless-stopped
  platform: linux/x86_64
  depends_on:
    - postgres
    - redis
  env_file:
    - ./.envs/.production/.django
    - ./.envs/.production/.postgres
  volumes:
    - ../scielo/www:/scielo_www
    - upload_media:/app/core/media

services:
  django:
    <<: *django-function
    container_name: upload_production_django
    ports:
      - "8000:8000"
    command: /start

  # nginx:
  #     image: nginx:latest
  #     container_name: upload_nginx
  #     volumes:
  #         - ./nginx/conf.d:/etc/nginx/conf.d
  #         - ./nginx/logs:/var/log/nginx/
  #     ports:
  #         - "81:80"


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: upload_production_postgres
    container_name: upload_production_postgres
    volumes:
      - ../scms_data/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/data_prod_backup:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6
    container_name: upload_production_redis

  celeryworker:
    <<: *django-function
    container_name: upload_production_celeryworker
    command: /start-celeryworker
    ports: []
    deploy:
      resources:
        limits:
          memory: 2.5G

  celerybeat:
    <<: *django-function
    container_name: upload_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django-function
    container_name: upload_production_flower
    command: /start-flower
    ports:
      - "5555:5555"


volumes:
  upload_media:
    name: upload_media
