# Generated by Django 4.1.10 on 2023-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "publication_initial_month_number",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "JANUARY"),
                            (2, "FEBRUARY"),
                            (3, "MARCH"),
                            (4, "APRIL"),
                            (5, "MAY"),
                            (6, "JUNE"),
                            (7, "JULY"),
                            (8, "AUGUST"),
                            (9, "SEPTEMBER"),
                            (10, "OCTOBER"),
                            (11, "NOVEMBER"),
                            (12, "DECEMBER"),
                        ],
                        null=True,
                        verbose_name="Publication initial month number",
                    ),
                ),
                (
                    "publication_initial_month_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Publication initial month name",
                    ),
                ),
                (
                    "publication_final_month_number",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "JANUARY"),
                            (2, "FEBRUARY"),
                            (3, "MARCH"),
                            (4, "APRIL"),
                            (5, "MAY"),
                            (6, "JUNE"),
                            (7, "JULY"),
                            (8, "AUGUST"),
                            (9, "SEPTEMBER"),
                            (10, "OCTOBER"),
                            (11, "NOVEMBER"),
                            (12, "DECEMBER"),
                        ],
                        null=True,
                        verbose_name="Publication final month number",
                    ),
                ),
                (
                    "publication_final_month_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Publication final month name",
                    ),
                ),
                (
                    "publication_date_text",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Publication date text"
                    ),
                ),
                (
                    "volume",
                    models.TextField(blank=True, null=True, verbose_name="Volume"),
                ),
                (
                    "number",
                    models.TextField(blank=True, null=True, verbose_name="Number"),
                ),
                (
                    "supplement",
                    models.TextField(blank=True, null=True, verbose_name="Supplement"),
                ),
                (
                    "publication_year",
                    models.TextField(blank=True, null=True, verbose_name="Year"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SciELOIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "issue_pid",
                    models.CharField(max_length=23, verbose_name="Issue PID"),
                ),
                (
                    "issue_folder",
                    models.CharField(max_length=23, verbose_name="Issue Folder"),
                ),
                (
                    "publication_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QA", "QA"),
                            ("APPROVED", "APPROVED"),
                            ("PUBLISHED", "PUBLISHED"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Publication stage",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="issue.issue",
                    ),
                ),
            ],
        ),
    ]
