# Generated by Django 4.2.6 on 2024-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="supplement",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Supplement"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="volume",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Volume"
            ),
        ),
    ]
