# Generated by Django 4.1.10 on 2023-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scieloissue",
            name="scielo_journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.scielojournal",
            ),
        ),
        migrations.AddField(
            model_name="scieloissue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="scieloissue",
            index=models.Index(
                fields=["issue_pid"], name="issue_sciel_issue_p_6052ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scieloissue",
            index=models.Index(
                fields=["issue_folder"], name="issue_sciel_issue_f_bb933b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scieloissue",
            unique_together={
                ("scielo_journal", "issue_pid"),
                ("scielo_journal", "issue_folder"),
                ("issue_pid", "issue_folder"),
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["journal"], name="issue_issue_journal_dcc9f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["publication_year"], name="issue_issue_publica_a3a5c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["volume"], name="issue_issue_volume_71bce1_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["number"], name="issue_issue_number_780a64_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["supplement"], name="issue_issue_supplem_bd88be_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={
                ("journal", "publication_year", "volume", "number", "supplement"),
                ("journal", "volume", "number", "supplement"),
            },
        ),
    ]
