# Generated by Django 3.2.12 on 2022-12-22 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='official_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.officialjournal'),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['official_journal'], name='issue_issue_officia_c32d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['publication_year'], name='issue_issue_publica_a3a5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['volume'], name='issue_issue_volume_71bce1_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['number'], name='issue_issue_number_780a64_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['supplement'], name='issue_issue_supplem_bd88be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('official_journal', 'volume', 'number', 'supplement'), ('official_journal', 'publication_year', 'volume', 'number', 'supplement')},
        ),
    ]
