# Generated by Django 3.2.12 on 2022-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_final_month_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Publication final month name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication_final_month_number',
            field=models.IntegerField(blank=True, choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], null=True, verbose_name='Publication final month number'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication_initial_month_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Publication initial month name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication_initial_month_number',
            field=models.IntegerField(blank=True, choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], null=True, verbose_name='Publication initial month number'),
        ),
    ]
