# Generated by Django 3.2.12 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20221222_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='supplement',
            field=models.TextField(blank=True, null=True, verbose_name='Supplement'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='volume',
            field=models.TextField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
