# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_auto_20230709_1941'),
        ('issue', '0004_auto_20230303_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.officialjournal'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication_year',
            field=models.TextField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='SciELOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('issue_pid', models.CharField(max_length=23, verbose_name='Issue PID')),
                ('issue_folder', models.CharField(max_length=23, verbose_name='Issue Folder')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scieloissue_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('official_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.issue')),
                ('scielo_journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.scielojournal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scieloissue_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddIndex(
            model_name='scieloissue',
            index=models.Index(fields=['scielo_journal'], name='issue_sciel_scielo__e6410c_idx'),
        ),
        migrations.AddIndex(
            model_name='scieloissue',
            index=models.Index(fields=['issue_pid'], name='issue_sciel_issue_p_6052ad_idx'),
        ),
        migrations.AddIndex(
            model_name='scieloissue',
            index=models.Index(fields=['issue_folder'], name='issue_sciel_issue_f_bb933b_idx'),
        ),
        migrations.AddIndex(
            model_name='scieloissue',
            index=models.Index(fields=['official_issue'], name='issue_sciel_officia_8dea60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scieloissue',
            unique_together={('scielo_journal', 'issue_pid'), ('issue_pid', 'issue_folder'), ('scielo_journal', 'issue_folder')},
        ),
    ]
