# Generated by Django 5.0.3 on 2024-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_pressrelease_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressrelease",
            name="doi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
