# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_pressrelease_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressrelease",
            name="doi",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
