# Generated by Django 5.0.3 on 2024-06-01 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_pressrelease_doi"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PressRelease",
        ),
    ]
