# Generated by Django 5.2.3 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_pressrelease_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressrelease",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
    ]
