# Generated by Django 4.2.6 on 2024-01-30 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websiteconfiguration",
            name="api_token",
        ),
        migrations.RemoveField(
            model_name="websiteconfiguration",
            name="db_name",
        ),
        migrations.RemoveField(
            model_name="websiteconfiguration",
            name="db_uri",
        ),
    ]
