# Generated by Django 3.2.12 on 2022-09-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0001_initial'),
        ('collection', '0002_journalcollections_scielojournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciELOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('issue_pid', models.CharField(max_length=17, verbose_name='Issue PID')),
                ('issue_folder', models.CharField(max_length=17, verbose_name='Issue Folder')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scieloissue_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('official_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue')),
                ('scielo_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scielojournal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scieloissue_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
