# Generated by Django 5.0.3 on 2024-06-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="max_absent_data_percentage_accepted",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="max_error_percentage_accepted",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="acron",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Collection Acronym"
            ),
        ),
        migrations.DeleteModel(
            name="WebSiteConfigurationEndpoint",
        ),
    ]
