# Generated by Django 3.2.12 on 2022-09-09 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0003_scieloissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='scielojournal',
            name='acron',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='scielojournal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='SciELODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid', models.CharField(blank=True, max_length=17, null=True, verbose_name='PID')),
                ('file_id', models.CharField(blank=True, max_length=17, null=True, verbose_name='File ID')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scielodocument_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('scielo_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scieloissue')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scielodocument_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
