# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20230303_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Language Name')),
                ('code2', models.TextField(blank=True, null=True, verbose_name='Language code 2')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.RemoveField(
            model_name='classicwebsiteconfiguration',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='classicwebsiteconfiguration',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='classicwebsiteconfiguration',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='filewithlang',
            name='scielofile_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='scielodocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='html_files',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='official_document',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='renditions_files',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='scielo_issue',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='xml_files',
        ),
        migrations.RemoveField(
            model_name='scielofile',
            name='scielo_issue',
        ),
        migrations.RemoveField(
            model_name='scielohtmlfile',
            name='assets_files',
        ),
        migrations.RemoveField(
            model_name='scielohtmlfile',
            name='filewithlang_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='scieloissue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scieloissue',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='scieloissue',
            name='official_issue',
        ),
        migrations.RemoveField(
            model_name='scieloissue',
            name='scielo_journal',
        ),
        migrations.RemoveField(
            model_name='scieloissue',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='scielojournal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scielojournal',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='scielojournal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='scielojournal',
            name='official_journal',
        ),
        migrations.RemoveField(
            model_name='scielojournal',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='assets_files',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='filewithlang_ptr',
        ),
        migrations.DeleteModel(
            name='AssetFile',
        ),
    ]
