# Generated by Django 3.2.12 on 2022-12-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20221222_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesstorageconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filesstorageconfiguration',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='filesstorageconfiguration',
            name='updated_by',
        ),
    ]
