# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20230709_1941'),
        ('migration', '0003_auto_20230709_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassicWebsiteConfiguration',
        ),
        migrations.DeleteModel(
            name='FileWithLang',
        ),
        migrations.DeleteModel(
            name='SciELODocument',
        ),
        migrations.DeleteModel(
            name='SciELOFile',
        ),
        migrations.DeleteModel(
            name='SciELOHTMLFile',
        ),
        migrations.DeleteModel(
            name='SciELOIssue',
        ),
        migrations.DeleteModel(
            name='SciELOJournal',
        ),
        migrations.DeleteModel(
            name='XMLFile',
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='language_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='language',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
