# Generated by Django 5.2.3 on 2026-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websiteconfiguration",
            name="api_get_token_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Get token API URL"
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfiguration",
            name="api_url_article",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Article API URL"
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfiguration",
            name="api_url_issue",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Issue API URL"
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfiguration",
            name="api_url_journal",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Journal API URL"
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfiguration",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Website URL"
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfigurationendpoint",
            name="url",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Endpoint URL"
            ),
        ),
    ]
