# Generated by Django 3.2.12 on 2022-09-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20220909_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalcollections',
            old_name='collections',
            new_name='scielo_journals',
        ),
    ]
