# Generated by Django 5.2.3 on 2026-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Collection URL"
            ),
        ),
    ]
