# Generated by Django 5.2.7 on 2026-09-23 14:51

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_alter_websiteconfiguration_api_get_token_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="network_classification",
            field=collection.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("scielonetwork", "SciELO Network"),
                        ("thematic", "Thematic"),
                        ("independent", "Independent"),
                    ],
                    max_length=20,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Network classification",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="platform_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classic", "Classic"),
                    ("new", "New"),
                    ("migrating", "Migrating"),
                    ("migrated", "Migrated"),
                ],
                max_length=20,
                null=True,
                verbose_name="Platform Status",
            ),
        ),
    ]
