# Generated by Django 3.2.12 on 2022-09-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0005_rename_collections_journalcollections_scielo_journals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scieloissue',
            name='official_issue',
        ),
        migrations.CreateModel(
            name='IssueInCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='issueincollections_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('official_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue')),
                ('scielo_issues', models.ManyToManyField(to='collection.SciELOIssue')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issueincollections_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
