# Generated by Django 3.2.12 on 2022-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_delete_filesstorageconfiguration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scielodocument',
            name='collection__file_id_a2e87a_idx',
        ),
        migrations.RemoveIndex(
            model_name='scielofile',
            name='collection__file_id_770a89_idx',
        ),
        migrations.RemoveIndex(
            model_name='scielofile',
            name='collection__object__dd3e6a_idx',
        ),
        migrations.RemoveField(
            model_name='scielofile',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='scielofile',
            name='object_name',
        ),
        migrations.AddField(
            model_name='scielodocument',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='File key'),
        ),
        migrations.AddField(
            model_name='scielofile',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File key'),
        ),
        migrations.AlterUniqueTogether(
            name='scielodocument',
            unique_together={('pid', 'key'), ('scielo_issue', 'pid'), ('scielo_issue', 'key')},
        ),
        migrations.AddIndex(
            model_name='scielodocument',
            index=models.Index(fields=['key'], name='collection__key_29c519_idx'),
        ),
        migrations.AddIndex(
            model_name='scielofile',
            index=models.Index(fields=['key'], name='collection__key_95cfa6_idx'),
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='file_id',
        ),
    ]
