# Generated by Django 5.2.3 on 2026-05-22 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0005_collection_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="url",
        ),
    ]
