# Generated by Django 3.2.12 on 2022-12-31 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20221222_1831'),
        ('files_storage', '0003_auto_20221231_0214'),
        ('journal', '0002_auto_20221229_1433'),
        ('collection', '0006_auto_20221229_1433'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='xmlfile',
            name='collection__v3_4868de_idx',
        ),
        migrations.RemoveField(
            model_name='scielodocument',
            name='renditions_files',
        ),
        migrations.RemoveField(
            model_name='scielofile',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='public_object_name',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='public_uri',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='v3',
        ),
        migrations.AddField(
            model_name='scielodocument',
            name='rendition_files',
            field=models.ManyToManyField(null=True, related_name='rendition_files', to='collection.FileWithLang'),
        ),
        migrations.AddField(
            model_name='scielofile',
            name='versions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_storage.fileversions'),
        ),
        migrations.AlterField(
            model_name='classicwebsiteconfiguration',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='scielodocument',
            name='scielo_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.scieloissue'),
        ),
        migrations.AlterField(
            model_name='scielofile',
            name='scielo_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.scieloissue'),
        ),
        migrations.AlterField(
            model_name='scieloissue',
            name='official_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.issue'),
        ),
        migrations.AlterField(
            model_name='scieloissue',
            name='scielo_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.scielojournal'),
        ),
        migrations.AlterField(
            model_name='scielojournal',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='scielojournal',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.officialjournal'),
        ),
    ]
