# Generated by Django 3.2.12 on 2022-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0003_auto_20221231_0214'),
        ('collection', '0007_auto_20221231_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scielofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename'),
        ),
        migrations.RemoveField(
            model_name='scielofile',
            name='versions',
        ),
        migrations.AddField(
            model_name='scielofile',
            name='versions',
            field=models.ManyToManyField(to='files_storage.MinioFile'),
        ),
    ]
