class TeamGroups:
    COLLECTION_ADMIN = "COLLECTION_TEAM_ADMIN"
    COLLECTION_MEMBER = "COLLECTION_TEAM_MEMBER"
    JOURNAL_ADMIN = "JOURNAL_TEAM_ADMIN"
    JOURNAL_MEMBER = "JOURNAL_TEAM_MEMBER"
    COMPANY_ADMIN = "COMPANY_TEAM_ADMIN"
    COMPANY_MEMBER = "COMPANY_MEMBER"
    ALL = (
        COLLECTION_ADMIN,
        COLLECTION_MEMBER,
        JOURNAL_ADMIN,
        JOURNAL_MEMBER,
        COMPANY_ADMIN,
        COMPANY_MEMBER,
    )
