# Generated by Django 5.0.3 on 2024-06-02 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="collectionteammember",
            name="team_collec_is_acti_e07ea4_idx",
        ),
    ]
