# Generated by Django 5.2.3 on 2026-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_company_companyteammember_journalcompanycontract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionteammember",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("member", "Member")],
                default="member",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionteammember",
            index=models.Index(
                fields=["collection", "role"],
                name="team_collec_collect_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionteammember",
            index=models.Index(
                fields=["user", "is_active_member"],
                name="team_collec_user_id_idx",
            ),
        ),
    ]
