# Generated by Django 5.2.3 on 2026-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_add_role_to_collectionteammember"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="collectionteammember",
            new_name="team_collec_collect_0ee96e_idx",
            old_name="team_collec_collect_idx",
        ),
        migrations.RenameIndex(
            model_name="collectionteammember",
            new_name="team_collec_user_id_6382ef_idx",
            old_name="team_collec_user_id_idx",
        ),
        migrations.AddField(
            model_name="company",
            name="certified_since",
            field=models.DateField(
                blank=True, null=True, verbose_name="Certified Since"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="personal_contact",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Personal Contact"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
