# Generated by Django 3.2.12 on 2022-09-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('researcher', '0001_initial'),
        ('doi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid_v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v3')),
                ('pid_v2', models.CharField(max_length=23, primary_key=True, serialize=False, verbose_name='PID v2')),
                ('aop_pid', models.CharField(blank=True, max_length=23, null=True, verbose_name='AOP PID')),
                ('elocation_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Elocation ID')),
                ('fpage', models.CharField(blank=True, max_length=16, null=True, verbose_name='First page')),
                ('lpage', models.CharField(blank=True, max_length=16, null=True, verbose_name='Last page')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.issue')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.officialjournal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('lang', models.CharField(max_length=64, verbose_name='Language')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articletitle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('title_with_lang', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_with_lang', to='article.article')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articletitle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('item_type', models.CharField(max_length=128, verbose_name='Related item type')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articlerelateditem_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('related_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='article.article')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlerelateditem_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleDOIWithLang',
            fields=[
                ('doiwithlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doi.doiwithlang')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('doi_with_lang', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_with_lang', to='article.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('doi.doiwithlang', models.Model),
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('researcher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researcher.researcher')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='article.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('researcher.researcher', models.Model),
        ),
    ]
