# Generated by Django 5.0.3 on 2024-08-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="articleauthor",
            name="researcher_ptr",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["position", "fpage", "-first_publication_date"],
                "permissions": (
                    ("make_article_change", "Can make article change"),
                    ("request_article_change", "Can request article change"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="articletitle",
            options={},
        ),
        migrations.RenameField(
            model_name="articletitle",
            old_name="title_with_lang",
            new_name="parent",
        ),
        migrations.RemoveField(
            model_name="articletitle",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="articletitle",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="articletitle",
            name="title",
        ),
        migrations.AddField(
            model_name="article",
            name="first_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="pid_v2",
            field=models.CharField(
                blank=True, max_length=23, null=True, verbose_name="PID v2"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="position",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Position"
            ),
        ),
    ]
