# Generated by Django 3.2.12 on 2022-09-12 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('make_article_change', 'Can make article change'), ('request_article_change', 'Can request article change'))},
        ),
        migrations.CreateModel(
            name='RequestArticleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('change_type', models.CharField(choices=[('errata', 'Errata'), ('correction', 'Correction')], max_length=32, verbose_name='Change type')),
                ('comment', wagtail.core.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='Comment')),
                ('pid_v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v3')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requestarticlechange_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('demanded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestarticlechange_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
