# Generated by Django 5.0.3 on 2025-06-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_remove_articleauthor_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Position"
            ),
        ),
    ]
