# Generated by Django 4.1.10 on 2023-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        ("article", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_items",
            field=models.ManyToManyField(
                related_name="related_to",
                through="article.RelatedItem",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="sps_pkg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="package.spspkg",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
