# Generated by Django 3.2.12 on 2022-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220921_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('change-submitted', 'Change submitted'), ('required-update', 'Required update'), ('required-erratum', 'Required erratum'), ('published', 'Publicado')], max_length=32, null=True, verbose_name='Article status'),
        ),
        migrations.AlterField(
            model_name='requestarticlechange',
            name='change_type',
            field=models.CharField(choices=[('update', 'Atualizar'), ('erratum', 'Erratum')], max_length=32, verbose_name='Change type'),
        ),
    ]
