# Generated by Django 5.0.8 on 2025-07-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_alter_article_position"),
        (
            "pid_provider",
            "0004_remove_otherpid_pid_provide_pid_in__f806db_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="pp_xml",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pid_provider.pidproviderxml",
            ),
        ),
    ]
