# Generated by Django 5.0.8 on 2025-08-26 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_article_pp_xml"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articledoiwithlang",
            options={
                "verbose_name": "Article DOI with Language",
                "verbose_name_plural": "Article DOIs with Language",
            },
        ),
        migrations.RenameField(
            model_name="articledoiwithlang",
            old_name="doi_with_lang",
            new_name="article",
        ),
    ]
