# Generated by Django 5.0.3 on 2024-08-20 11:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_remove_requestarticlechange_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestarticlechange",
            name="comment",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Comment"
            ),
        ),
    ]
