# Generated by Django 5.2.3 on 2025-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_alter_articledoiwithlang_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abstract", "Abstract"),
                    ("addendum", "Addendum"),
                    ("announcement", "Announcement"),
                    ("article-commentary", "Article-Commentary"),
                    ("book-review", "Book-Review"),
                    ("books-received", "Books-Received"),
                    ("brief-report", "Brief-Report"),
                    ("calendar", "Calendar"),
                    ("case-report", "Case-Report"),
                    ("clinical-trial", "Clinical-Trial"),
                    ("collection", "Collection"),
                    ("correction", "Correction"),
                    ("data-article", "Data-Article"),
                    ("discussion", "Discussion"),
                    ("dissertation", "Dissertation"),
                    ("editorial", "Editorial"),
                    ("editorial-material", "Editorial-Material"),
                    ("guideline", "Guideline"),
                    ("in-brief", "In-Brief"),
                    ("interview", "Interview"),
                    ("introduction", "Introduction"),
                    ("letter", "Letter"),
                    ("meeting-report", "Meeting-Report"),
                    ("news", "News"),
                    ("obituary", "Obituary"),
                    ("oration", "Oration"),
                    ("other", "Other"),
                    ("partial-retraction", "Partial-Retraction"),
                    ("product-review", "Product-Review"),
                    ("rapid-communication", "Rapid-Communication"),
                    ("reply", "Reply"),
                    ("reprint", "Reprint"),
                    ("research-article", "Research-Article"),
                    ("retraction", "Retraction"),
                    ("review-article", "Review-Article"),
                    ("technical-report", "Technical-Report"),
                    ("translation", "Translation"),
                ],
                max_length=32,
                null=True,
                verbose_name="Article type",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("erratum-submitted", "Erratum submitted"),
                    ("update-submitted", "Update submitted"),
                    ("required-update", "Required update"),
                    ("required-erratum", "Required erratum"),
                    ("prepare-to-publish", "Prepare to publish"),
                    ("ready-to-publish", "Ready to publish"),
                    ("scheduled-to-publish", "Scheduled to publish"),
                    ("published", "Published"),
                ],
                max_length=32,
                null=True,
                verbose_name="Article status",
            ),
        ),
        migrations.AlterField(
            model_name="requestarticlechange",
            name="change_type",
            field=models.CharField(
                choices=[("update", "Update"), ("erratum", "Erratum")],
                max_length=32,
                verbose_name="Change type",
            ),
        ),
    ]
