# Generated by Django 5.0.3 on 2024-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_alter_requestarticlechange_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestarticlechange",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
