# Generated by Django 3.2.19 on 2023-07-09 19:41

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20230303_1026'),
        ('journal', '0002_auto_20230303_1026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0004_auto_20230303_1026'),
        ('article', '0006_article_xml_sps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('category', models.TextField(verbose_name='Category')),
                ('sps_filename', models.TextField(verbose_name='SPS filename')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='aop_pid',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pid_v2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='xml_sps',
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.issue'),
        ),
        migrations.CreateModel(
            name='FormerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('href', models.TextField(blank=True, null=True, verbose_name='Classic website location')),
                ('collection_acron', models.TextField(verbose_name='Collection acron')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='formerlocation_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formerlocation_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionArticleId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid_v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v3')),
                ('pid_v2', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v2')),
                ('aop_pid', models.CharField(blank=True, max_length=23, null=True, verbose_name='AOP PID')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='collectionarticleid_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectionarticleid_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('sps_pkg_name', models.TextField(blank=True, null=True, verbose_name='New name')),
                ('optimised_zip_file', models.FileField(blank=True, null=True, upload_to=article.models.optimised_sps_packages_directory_path)),
                ('not_optimised_zip_file', models.FileField(blank=True, null=True, upload_to=article.models.not_optimised_sps_packages_directory_path)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article')),
                ('components', models.ManyToManyField(to='article.ArticleComponent')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articlepackages_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlepackages_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddField(
            model_name='articlecomponent',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
        migrations.AddField(
            model_name='articlecomponent',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articlecomponent_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='articlecomponent',
            name='former_locations',
            field=models.ManyToManyField(to='article.FormerLocation', verbose_name='Classic website locations'),
        ),
    ]
