# Generated by Django 5.2.3 on 2025-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0006_alter_article_article_type_alter_article_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["position", "fpage", "-first_pubdate_iso"],
                "permissions": (
                    ("make_article_change", "Can make article change"),
                    ("request_article_change", "Can request article change"),
                ),
            },
        ),
        migrations.AddField(
            model_name="article",
            name="first_pubdate_iso",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="First publication date ISO",
            ),
        ),
    ]
