# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20230709_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_auto_20230709_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomponent',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.language'),
        ),
        migrations.AddField(
            model_name='articlecomponent',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlecomponent_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='article',
            name='aids',
            field=models.ManyToManyField(to='article.CollectionArticleId'),
        ),
        migrations.AddIndex(
            model_name='formerlocation',
            index=models.Index(fields=['collection_acron'], name='article_for_collect_731c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='formerlocation',
            index=models.Index(fields=['href'], name='article_for_href_7104ec_idx'),
        ),
        migrations.AddIndex(
            model_name='articlepackages',
            index=models.Index(fields=['article'], name='article_art_article_216263_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomponent',
            index=models.Index(fields=['article'], name='article_art_article_94ca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomponent',
            index=models.Index(fields=['sps_filename'], name='article_art_sps_fil_c76b38_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomponent',
            index=models.Index(fields=['category'], name='article_art_categor_bfaf46_idx'),
        ),
    ]
