# Generated by Django 5.2.3 on 2026-03-16 23:00

from django.db import migrations, models


def remove_duplicate_articles(apps, schema_editor):
    """Remove duplicate Article records with the same pid_v3, keeping the most recently updated one."""
    Article = apps.get_model("article", "Article")
    from django.db.models import Count

    duplicates = (
        Article.objects.values("pid_v3")
        .exclude(pid_v3__isnull=True)
        .exclude(pid_v3="")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        pid_v3 = dup["pid_v3"]
        items = Article.objects.filter(pid_v3=pid_v3).order_by("-updated")
        # Keep the most recently updated, delete the rest
        for item in items[1:]:
            item.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0007_alter_article_options_article_first_pubdate_iso"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_articles,
            migrations.RunPython.noop,
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_pid_v3_2370cc_idx",
        ),
        migrations.AlterField(
            model_name="article",
            name="pid_v3",
            field=models.CharField(
                blank=True, max_length=23, null=True, unique=True, verbose_name="PID v3"
            ),
        ),
    ]
