# Generated by Django 5.2.3 on 2026-05-22 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0008_add_unique_pid_v3"),
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="fpage_seq",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="First page seq"
            ),
        ),
        migrations.CreateModel(
            name="ArticleCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("partial-checked", "Partially checked"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("valid_content", "Valid content"),
                            ("content_mismatch", "Content mismatch"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_collections",
                        to="article.article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_collections",
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article collection",
                "verbose_name_plural": "Article collections",
                "indexes": [
                    models.Index(
                        fields=["collection", "status"],
                        name="article_art_collect_c2dfc0_idx",
                    ),
                    models.Index(
                        fields=["article", "status"],
                        name="article_art_article_c5e2d2_idx",
                    ),
                ],
                "unique_together": {("article", "collection")},
            },
        ),
        migrations.CreateModel(
            name="ArticleWebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUBLIC", "Public"),
                            ("QA", "QA"),
                            ("CLASSIC", "Classic"),
                        ],
                        help_text="Distinguishes between public, QA, and classic website pages.",
                        max_length=8,
                        null=True,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "fmt",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Format"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=265, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("partial-checked", "Partially checked"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("valid_content", "Valid content"),
                            ("content_mismatch", "Content mismatch"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=16,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, null=True, verbose_name="Detail"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="article.article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.language",
                        verbose_name="Language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article web page",
                "verbose_name_plural": "Article web pages",
                "indexes": [
                    models.Index(
                        fields=["article", "collection", "status"],
                        name="article_art_article_c12193_idx",
                    ),
                    models.Index(
                        fields=["article", "collection", "purpose"],
                        name="article_art_article_4c7ded_idx",
                    ),
                    models.Index(
                        fields=["purpose", "status"],
                        name="article_art_purpose_eb556f_idx",
                    ),
                ],
                "unique_together": {
                    ("article", "collection", "purpose", "fmt", "lang")
                },
            },
        ),
    ]
