# Generated by Django 5.2.3 on 2026-05-12 23:57

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0008_add_unique_pid_v3"),
        ("collection", "0005_collection_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleWebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "fmt",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Format"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=265, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("valid_content", "Valid content"),
                            ("content_mismatch", "Content mismatch"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=16,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, null=True, verbose_name="Detail"),
                ),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_webpages",
                        to="article.article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.language",
                        verbose_name="Language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["url"], name="article_art_url_152ec8_idx"),
                    models.Index(
                        fields=["article", "collection", "fmt", "lang"],
                        name="article_art_article_b0d342_idx",
                    ),
                ],
                "unique_together": {("article", "collection", "url", "fmt", "lang")},
            },
        ),
    ]
