# Generated by Django 5.2.3 on 2026-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0008_add_unique_pid_v3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pid_v3",
            field=models.CharField(
                blank=True, max_length=23, null=True, unique=True, verbose_name="PID v3"
            ),
        ),
    ]
