# Generated by Django 5.2.3 on 2026-05-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0009_article_fpage_seq_articlecollection_articlewebpage"),
        ("collection", "0005_alter_websiteconfiguration_api_get_token_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collection.collection"
            ),
        ),
        migrations.AlterField(
            model_name="articlewebpage",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collection.collection",
            ),
        ),
    ]
