# Generated by Django 5.2.3 on 2026-05-25 10:54

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0010_alter_articlecollection_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecollection",
            name="article",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_collections",
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="articlewebpage",
            name="article",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="article.article",
            ),
        ),
    ]
