# Generated by Django 3.2.12 on 2022-09-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='affiliations',
            field=models.ManyToManyField(blank=True, to='researcher.ResearcherAffiliation'),
        ),
    ]
