# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="gender_identification_status",
            field=models.CharField(
                choices=[
                    ("DECLARED", "Declarado por el investigador"),
                    (
                        "AUTOMATIC",
                        "Identificado automáticamente por programa de computador",
                    ),
                    ("MANUAL", "Identificado por algun usuario"),
                ],
                max_length=10,
                verbose_name="Gender identification status",
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="lattes",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Lattes"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="orcid",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="ORCID"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="suffix",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Suffix"
            ),
        ),
    ]
