# Generated by Django 3.2.12 on 2022-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='affiliations',
            field=models.ManyToManyField(to='researcher.ResearcherAffiliation'),
        ),
    ]
