# Generated by Django 3.2.12 on 2023-01-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('researcher', '0002_auto_20230123_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Editor-Chefe', 'Editor-Chefe'), ('Editor(es) Executivo', 'Editor(es) Executivo'), ('Editor(es) Associados ou de Seção', 'Editor(es) Associados ou de Seção'), ('Equipe Técnica', 'Equipe Técnica')], max_length=255, verbose_name='Role')),
                ('initial_year', models.IntegerField(blank=True, null=True)),
                ('initial_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('final_year', models.IntegerField(blank=True, null=True)),
                ('final_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journal.journal')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='researcher.researcher')),
            ],
        ),
    ]
