# Generated by Django 4.2.6 on 2024-03-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="journal",
            field=models.ManyToManyField(
                blank=True, to="journal.journal", verbose_name="Journal"
            ),
        ),
    ]
