# Generated by Django 4.2.6 on 2023-12-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import migration.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MigratedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="Origin"
                    ),
                ),
                (
                    "isis_updated_date",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="ISIS updated date",
                    ),
                ),
                (
                    "isis_created_date",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="ISIS created date",
                    ),
                ),
                (
                    "migration_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Migration Status",
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigratedArticle",
            fields=[
                (
                    "migrateddata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="migration.migrateddata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("migration.migrateddata",),
        ),
        migrations.CreateModel(
            name="MigratedIssue",
            fields=[
                (
                    "migrateddata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="migration.migrateddata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("migration.migrateddata",),
        ),
        migrations.CreateModel(
            name="MigratedJournal",
            fields=[
                (
                    "migrateddata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="migration.migrateddata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("migration.migrateddata",),
        ),
        migrations.CreateModel(
            name="ClassicWebsiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title_path",
                    models.CharField(
                        blank=True,
                        help_text="Title path: title.id path or title.mst path without extension",
                        max_length=255,
                        null=True,
                        verbose_name="Title path",
                    ),
                ),
                (
                    "issue_path",
                    models.CharField(
                        blank=True,
                        help_text="Issue path: issue.id path or issue.mst path without extension",
                        max_length=255,
                        null=True,
                        verbose_name="Issue path",
                    ),
                ),
                (
                    "serial_path",
                    models.CharField(
                        blank=True,
                        help_text="Serial path",
                        max_length=255,
                        null=True,
                        verbose_name="Serial path",
                    ),
                ),
                (
                    "cisis_path",
                    models.CharField(
                        blank=True,
                        help_text="Cisis path where there are CISIS utilities such as mx and i2id",
                        max_length=255,
                        null=True,
                        verbose_name="Cisis path",
                    ),
                ),
                (
                    "bases_work_path",
                    models.CharField(
                        blank=True,
                        help_text="Bases work path",
                        max_length=255,
                        null=True,
                        verbose_name="Bases work path",
                    ),
                ),
                (
                    "bases_pdf_path",
                    models.CharField(
                        blank=True,
                        help_text="Bases translation path",
                        max_length=255,
                        null=True,
                        verbose_name="Bases pdf path",
                    ),
                ),
                (
                    "bases_translation_path",
                    models.CharField(
                        blank=True,
                        help_text="Bases translation path",
                        max_length=255,
                        null=True,
                        verbose_name="Bases translation path",
                    ),
                ),
                (
                    "bases_xml_path",
                    models.CharField(
                        blank=True,
                        help_text="Bases XML path",
                        max_length=255,
                        null=True,
                        verbose_name="Bases XML path",
                    ),
                ),
                (
                    "htdocs_img_revistas_path",
                    models.CharField(
                        blank=True,
                        help_text="Htdocs img revistas path",
                        max_length=255,
                        null=True,
                        verbose_name="Htdocs img revistas path",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=migration.models.migrated_files_directory_path,
                    ),
                ),
                (
                    "original_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="Original Path"
                    ),
                ),
                (
                    "original_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Original name"
                    ),
                ),
                ("file_date", models.DateField(blank=True, null=True)),
                (
                    "original_href",
                    models.TextField(
                        blank=True, null=True, verbose_name="Original href"
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Component type",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Language"
                    ),
                ),
                (
                    "pkg_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Pkg name"
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="Part"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["original_name"], name="migration_m_origina_3b6f90_idx"
                    ),
                    models.Index(
                        fields=["original_path"], name="migration_m_origina_ba75f0_idx"
                    ),
                    models.Index(
                        fields=["original_href"], name="migration_m_origina_f9a602_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="migrateddata",
            index=models.Index(
                fields=["content_type"], name="migration_m_content_0caadf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrateddata",
            index=models.Index(fields=["pid"], name="migration_m_pid_508b1a_idx"),
        ),
        migrations.AddIndex(
            model_name="migrateddata",
            index=models.Index(
                fields=["migration_status"], name="migration_m_migrati_62f21d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classicwebsiteconfiguration",
            index=models.Index(
                fields=["collection"], name="migration_c_collect_99e14a_idx"
            ),
        ),
    ]
