# Generated by Django 3.2.12 on 2022-09-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid', models.CharField(max_length=23, verbose_name='Item PID')),
                ('exception_type', models.CharField(max_length=255, verbose_name='Exception Type')),
                ('exception_msg', models.CharField(max_length=255, verbose_name='Exception Msg')),
                ('action_name', models.CharField(max_length=255, verbose_name='Action')),
                ('object_name', models.CharField(max_length=255, verbose_name='Object')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migrationfailure_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrationfailure_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MigratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('isis_updated_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISIS updated date')),
                ('isis_created_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISIS created date')),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('TO_MIGRATE', 'To migrate'), ('MIGRATED', 'Migrated'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', max_length=20, verbose_name='Status')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migrateddata_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrateddata_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
