# Generated by Django 3.2.12 on 2022-12-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20221223_1515'),
        ('files_storage', '0001_initial'),
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='files_storage_config',
        ),
        migrations.AddField(
            model_name='migrationconfiguration',
            name='migration_files_storage_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_files_storage_config', to='files_storage.configuration', verbose_name='Migration Files Storage Configuration'),
        ),
        migrations.AddField(
            model_name='migrationconfiguration',
            name='public_files_storage_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_files_storage_config', to='files_storage.configuration', verbose_name='Public Files Storage Configuration'),
        ),
        migrations.AlterField(
            model_name='migrationconfiguration',
            name='classic_website_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.classicwebsiteconfiguration', verbose_name='Classic website configuration'),
        ),
        migrations.AlterField(
            model_name='migrationconfiguration',
            name='new_website_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.newwebsiteconfiguration', verbose_name='New website configuration'),
        ),
    ]
