# Generated by Django 4.2.6 on 2024-01-26 22:52

from django.db import migrations, models
import migration.models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="migratedarticle",
            name="components",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migratedarticle",
            name="texts",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migratedarticle",
            name="zip_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=migration.models.migrated_files_directory_path,
            ),
        ),
    ]
