# Generated by Django 4.2.6 on 2024-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migrateddata",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Migration Status",
            ),
        ),
    ]
