# Generated by Django 5.0.3 on 2024-07-04 16:06

import django.db.models.deletion
import migration.models
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
        ("journal", "0003_journal_journal_acron"),
        ("migration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="migratedarticle",
            name="file_type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=4,
                null=True,
                verbose_name="File type",
            ),
        ),
        migrations.CreateModel(
            name="JournalAcronIdFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=migration.models.migrated_files_directory_path,
                    ),
                ),
                (
                    "source_path",
                    models.TextField(blank=True, null=True, verbose_name="Source"),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journal.journal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdFileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("data", models.JSONField()),
                ("item_pid", models.CharField(max_length=23, verbose_name="PID")),
                ("item_type", models.CharField(max_length=10, verbose_name="Type")),
                (
                    "issue_folder",
                    models.CharField(max_length=30, verbose_name="Issue folder"),
                ),
                (
                    "article_filename",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Filename"
                    ),
                ),
                (
                    "article_filetype",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="File type"
                    ),
                ),
                (
                    "processing_date",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_file_records",
                        to="migration.journalacronidfile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="journalacronidfile",
            index=models.Index(
                fields=["source_path"], name="migration_j_source__acebff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalacronidfile",
            unique_together={("collection", "journal", "source_path")},
        ),
        migrations.AddIndex(
            model_name="idfilerecord",
            index=models.Index(
                fields=["parent"], name="migration_i_parent__566149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idfilerecord",
            index=models.Index(
                fields=["item_pid"], name="migration_i_item_pi_1d6f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idfilerecord",
            index=models.Index(
                fields=["item_type"], name="migration_i_item_ty_a624ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idfilerecord",
            index=models.Index(
                fields=["issue_folder"], name="migration_i_issue_f_fcc1a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="idfilerecord",
            unique_together={("parent", "item_type", "item_pid")},
        ),
    ]
