# Generated by Django 3.2.12 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationfailure',
            name='action_name',
            field=models.TextField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='exception_msg',
            field=models.TextField(verbose_name='Exception Msg'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='exception_type',
            field=models.TextField(verbose_name='Exception Type'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='object_name',
            field=models.TextField(verbose_name='Object'),
        ),
    ]
