# Generated by Django 3.2.19 on 2023-07-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import migration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_auto_20230709_1941'),
        ('article', '0008_auto_20230709_1941'),
        ('collection', '0004_auto_20230709_1941'),
        ('issue', '0005_auto_20230709_1941'),
        ('migration', '0002_auto_20230303_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAndBackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('file', models.FileField(blank=True, null=True, upload_to=migration.models.body_and_back_directory_path)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassicWebsiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('title_path', models.CharField(blank=True, help_text='Title path: title.id path or title.mst path without extension', max_length=255, null=True, verbose_name='Title path')),
                ('issue_path', models.CharField(blank=True, help_text='Issue path: issue.id path or issue.mst path without extension', max_length=255, null=True, verbose_name='Issue path')),
                ('serial_path', models.CharField(blank=True, help_text='Serial path', max_length=255, null=True, verbose_name='Serial path')),
                ('cisis_path', models.CharField(blank=True, help_text='Cisis path where there are CISIS utilities such as mx and i2id', max_length=255, null=True, verbose_name='Cisis path')),
                ('bases_work_path', models.CharField(blank=True, help_text='Bases work path', max_length=255, null=True, verbose_name='Bases work path')),
                ('bases_pdf_path', models.CharField(blank=True, help_text='Bases translation path', max_length=255, null=True, verbose_name='Bases pdf path')),
                ('bases_translation_path', models.CharField(blank=True, help_text='Bases translation path', max_length=255, null=True, verbose_name='Bases translation path')),
                ('bases_xml_path', models.CharField(blank=True, help_text='Bases XML path', max_length=255, null=True, verbose_name='Bases XML path')),
                ('htdocs_img_revistas_path', models.CharField(blank=True, help_text='Htdocs img revistas path', max_length=255, null=True, verbose_name='Htdocs img revistas path')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedXMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('file', models.FileField(blank=True, null=True, upload_to=migration.models.generated_xml_directory_path)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MigratedDocument',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('pid', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('sps_pkg_name', models.TextField(blank=True, null=True, verbose_name='New Package name')),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='MigratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('file', models.FileField(blank=True, null=True, upload_to=migration.models.migrated_files_directory_path)),
                ('original_path', models.TextField(blank=True, null=True, verbose_name='Original Path')),
                ('original_href', models.TextField(blank=True, null=True, verbose_name='Original href')),
                ('original_name', models.TextField(blank=True, null=True, verbose_name='Original name')),
                ('sps_pkg_name', models.TextField(blank=True, null=True, verbose_name='New name')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issue File Category')),
                ('part', models.CharField(blank=True, max_length=6, null=True, verbose_name='Part')),
            ],
        ),
        migrations.CreateModel(
            name='MigratedIssue',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='MigratedJournal',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.RemoveField(
            model_name='documentmigration',
            name='migrateddata_ptr',
        ),
        migrations.RemoveField(
            model_name='documentmigration',
            name='scielo_document',
        ),
        migrations.RemoveField(
            model_name='issuemigration',
            name='migrateddata_ptr',
        ),
        migrations.RemoveField(
            model_name='issuemigration',
            name='scielo_issue',
        ),
        migrations.RemoveField(
            model_name='journalmigration',
            name='migrateddata_ptr',
        ),
        migrations.RemoveField(
            model_name='journalmigration',
            name='scielo_journal',
        ),
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='classic_website_config',
        ),
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='files_storage_config',
        ),
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='new_website_config',
        ),
        migrations.RemoveField(
            model_name='migrationconfiguration',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='migrationfailure',
            name='migration_m_object__d510e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='migrationfailure',
            name='migration_m_pid_c2722d_idx',
        ),
        migrations.RemoveField(
            model_name='migrationfailure',
            name='object_name',
        ),
        migrations.RemoveField(
            model_name='migrationfailure',
            name='pid',
        ),
        migrations.AddField(
            model_name='migrationfailure',
            name='collection_acron',
            field=models.TextField(blank=True, null=True, verbose_name='Collection acron'),
        ),
        migrations.AddField(
            model_name='migrationfailure',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='migrationfailure',
            name='migrated_item_id',
            field=models.TextField(blank=True, null=True, verbose_name='Item id'),
        ),
        migrations.AddField(
            model_name='migrationfailure',
            name='migrated_item_name',
            field=models.TextField(blank=True, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='action_name',
            field=models.TextField(blank=True, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='exception_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Exception Msg'),
        ),
        migrations.AlterField(
            model_name='migrationfailure',
            name='exception_type',
            field=models.TextField(blank=True, null=True, verbose_name='Exception Type'),
        ),
        migrations.DeleteModel(
            name='DocumentMigration',
        ),
        migrations.DeleteModel(
            name='IssueMigration',
        ),
        migrations.DeleteModel(
            name='JournalMigration',
        ),
        migrations.DeleteModel(
            name='MigrationConfiguration',
        ),
        migrations.AddField(
            model_name='migratedjournal',
            name='scielo_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.scielojournal'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='migrated_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedjournal'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='scielo_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.scieloissue'),
        ),
        migrations.AddField(
            model_name='migratedfile',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migratedfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='migratedfile',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.language'),
        ),
        migrations.AddField(
            model_name='migratedfile',
            name='migrated_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedissue'),
        ),
        migrations.AddField(
            model_name='migratedfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migratedfile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='aids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.collectionarticleid'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='migrated_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedissue'),
        ),
        migrations.AddField(
            model_name='generatedxmlfile',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='generatedxmlfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='generatedxmlfile',
            name='migrated_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedissue'),
        ),
        migrations.AddField(
            model_name='generatedxmlfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatedxmlfile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='classicwebsiteconfiguration',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='classicwebsiteconfiguration',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='classicwebsiteconfiguration_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='classicwebsiteconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classicwebsiteconfiguration_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='bodyandbackfile',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bodyandbackfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='bodyandbackfile',
            name='migrated_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedissue'),
        ),
        migrations.AddField(
            model_name='bodyandbackfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodyandbackfile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['scielo_journal'], name='migration_m_scielo__c30999_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['scielo_issue'], name='migration_m_scielo__94bf93_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['migrated_journal'], name='migration_m_migrate_867c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['pkg_name'], name='migration_m_pkg_nam_488997_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['migrated_issue'], name='migration_m_migrate_216e60_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['lang'], name='migration_m_lang_id_ed248e_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['part'], name='migration_m_part_eaf0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['category'], name='migration_m_categor_b8f513_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['original_href'], name='migration_m_origina_f9a602_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['original_name'], name='migration_m_origina_3b6f90_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['sps_pkg_name'], name='migration_m_sps_pkg_d6e535_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['migrated_issue'], name='migration_m_migrate_db24e4_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['pid'], name='migration_m_pid_9c9c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['pkg_name'], name='migration_m_pkg_nam_2bd7db_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedxmlfile',
            index=models.Index(fields=['pkg_name'], name='migration_g_pkg_nam_7fd008_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedxmlfile',
            index=models.Index(fields=['migrated_issue'], name='migration_g_migrate_2b9f59_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedxmlfile',
            index=models.Index(fields=['version'], name='migration_g_version_d2e575_idx'),
        ),
        migrations.AddIndex(
            model_name='classicwebsiteconfiguration',
            index=models.Index(fields=['collection'], name='migration_c_collect_99e14a_idx'),
        ),
        migrations.AddIndex(
            model_name='bodyandbackfile',
            index=models.Index(fields=['pkg_name'], name='migration_b_pkg_nam_61bb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='bodyandbackfile',
            index=models.Index(fields=['migrated_issue'], name='migration_b_migrate_3d5b03_idx'),
        ),
        migrations.AddIndex(
            model_name='bodyandbackfile',
            index=models.Index(fields=['version'], name='migration_b_version_45e57b_idx'),
        ),
    ]
