# Generated by Django 5.0.3 on 2024-07-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
        ("journal", "0004_journalsection"),
        ("migration", "0002_migratedarticle_file_type_journalacronidfile_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journalacronidfile",
            unique_together={("collection", "journal", "source_path")},
        ),
        migrations.AddField(
            model_name="journalacronidfile",
            name="collection_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="migration.migratedjournal",
            ),
        ),
        migrations.AddField(
            model_name="journalacronidfile",
            name="journal_acron",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="journalacronidfile",
            unique_together={
                ("collection", "journal", "source_path"),
                ("collection", "journal_acron", "source_path"),
            },
        ),
    ]
