# Generated by Django 5.0.3 on 2025-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0003_alter_journalacronidfile_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idfilerecord",
            name="article_filename",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Filename"
            ),
        ),
    ]
