# Generated by Django 4.2.6 on 2023-12-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0004_alter_bodyandbackfile_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigratedArticle",
            fields=[
                (
                    "migrateddata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="migration.migrateddata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("migration.migrateddata",),
        ),
    ]
