# Generated by Django 5.0.3 on 2025-02-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0004_alter_idfilerecord_article_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classicwebsiteconfiguration",
            name="cisis_path",
        ),
        migrations.AddField(
            model_name="classicwebsiteconfiguration",
            name="pid_list_path",
            field=models.CharField(
                blank=True,
                help_text="Path of a text file which contains all the article PIDs from artigo.mst",
                max_length=255,
                null=True,
                verbose_name="PID list path",
            ),
        ),
    ]
