# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0005_remove_classicwebsiteconfiguration_cisis_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalacronidfile",
            name="source_path",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Source"
            ),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="original_href",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Original href"
            ),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Original name"
            ),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="original_path",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Original Path"
            ),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Pkg name"
            ),
        ),
    ]
