# Generated by Django 5.0.3 on 2025-05-13 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0006_alter_journalacronidfile_source_path_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="idfilerecord",
            name="migration_i_issue_f_fcc1a8_idx",
        ),
    ]
