# Generated by Django 5.0.3 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0006_alter_journalacronidfile_source_path_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="idfilerecord",
            name="migration_i_issue_f_fcc1a8_idx",
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Original name"
            ),
        ),
    ]
