# Generated by Django 5.0.3 on 2025-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "migration",
            "0007_remove_idfilerecord_migration_i_issue_f_fcc1a8_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idfilerecord",
            name="article_filename",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="article_filetype",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="issue_folder",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="processing_date",
        ),
        migrations.AddField(
            model_name="classicwebsiteconfiguration",
            name="alternative_htdocs_img_revistas_path",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idfilerecord",
            name="todo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pkg name"
            ),
        ),
    ]
