# Generated by Django 5.0.3 on 2025-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "migration",
            "0007_remove_idfilerecord_migration_i_issue_f_fcc1a8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classicwebsiteconfiguration",
            name="alternative_htdocs_img_revistas_path",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
