# Generated by Django 5.0.3 on 2025-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "migration",
            "0008_classicwebsiteconfiguration_alternative_htdocs_img_revistas_path",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idfilerecord",
            name="article_filename",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="article_filetype",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="issue_folder",
        ),
        migrations.RemoveField(
            model_name="idfilerecord",
            name="processing_date",
        ),
        migrations.AddField(
            model_name="idfilerecord",
            name="todo",
            field=models.BooleanField(default=True),
        ),
    ]
