# Generated by Django 5.0.8 on 2025-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0008_remove_idfilerecord_article_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migratedfile",
            name="file_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
