# Generated by Django 5.2.3 on 2025-09-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0009_alter_migratedfile_file_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="migratedfile",
            name="file_date",
        ),
        migrations.AddField(
            model_name="migratedfile",
            name="file_datetime_iso",
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
