# Generated by Django 5.2.3 on 2026-02-11 18:16

import migration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0010_remove_migratedfile_file_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalacronidfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=migration.models.migrated_files_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="journalacronidfile",
            name="source_path",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Source"
            ),
        ),
        migrations.AlterField(
            model_name="migratedfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=migration.models.migrated_files_directory_path,
            ),
        ),
    ]
