# Generated by Django 5.2.3 on 2026-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0011_alter_journalacronidfile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classicwebsiteconfiguration",
            name="url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Collection URL"
            ),
        ),
    ]
