# Generated by Django 5.2.3 on 2026-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0012_classicwebsiteconfiguration_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classicwebsiteconfiguration",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Collection URL"
            ),
        ),
    ]
