# Generated by Django 4.2.6 on 2023-12-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issue", "0001_initial"),
        ("migration", "0001_initial"),
        ("collection", "0001_initial"),
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalProc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID"
                    ),
                ),
                (
                    "migration_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "qa_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="QA Website Status",
                    ),
                ),
                (
                    "public_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Public Website Status",
                    ),
                ),
                ("error_detail", models.JSONField(blank=True, null=True)),
                ("error_found", models.BooleanField(blank=True, null=True)),
                ("error_date", models.DateTimeField(blank=True, null=True)),
                (
                    "acron",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Acronym"
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Title"),
                ),
                (
                    "availability_status",
                    models.CharField(
                        blank=True,
                        choices=[("?", "Unknown"), ("C", "Current")],
                        max_length=10,
                        null=True,
                        verbose_name="Availability Status",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journal.journal",
                    ),
                ),
                (
                    "migrated_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="migration.migrateddata",
                    ),
                ),
                ("operations", models.ManyToManyField(to="proc.operation")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueProc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID"
                    ),
                ),
                (
                    "migration_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "qa_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="QA Website Status",
                    ),
                ),
                (
                    "public_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Public Website Status",
                    ),
                ),
                ("error_detail", models.JSONField(blank=True, null=True)),
                ("error_found", models.BooleanField(blank=True, null=True)),
                ("error_date", models.DateTimeField(blank=True, null=True)),
                (
                    "issue_folder",
                    models.CharField(max_length=23, verbose_name="Issue Folder"),
                ),
                (
                    "files_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Files migration status",
                    ),
                ),
                (
                    "docs_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Document records migration status",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="issue.issue",
                    ),
                ),
                ("issue_files", models.ManyToManyField(to="migration.migratedfile")),
                (
                    "journal_proc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proc.journalproc",
                    ),
                ),
                (
                    "migrated_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="migration.migrateddata",
                    ),
                ),
                ("operations", models.ManyToManyField(to="proc.operation")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleProc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=package.models.basic_xml_directory_path,
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID"
                    ),
                ),
                (
                    "migration_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "qa_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="QA Website Status",
                    ),
                ),
                (
                    "public_ws_status",
                    models.CharField(
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        verbose_name="Public Website Status",
                    ),
                ),
                ("error_detail", models.JSONField(blank=True, null=True)),
                ("error_found", models.BooleanField(blank=True, null=True)),
                ("error_date", models.DateTimeField(blank=True, null=True)),
                (
                    "pkg_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Package name"
                    ),
                ),
                (
                    "xml_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        null=True,
                        verbose_name="XML status",
                    ),
                ),
                (
                    "sps_pkg_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REPROC", "To reprocess"),
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("DOING", "Doing"),
                            ("PENDING", "Pending"),
                            ("IGNORED", "ignored"),
                        ],
                        default="TODO",
                        max_length=8,
                        null=True,
                        verbose_name="SPS Pkg status",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "issue_proc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proc.issueproc",
                    ),
                ),
                (
                    "migrated_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="migration.migrateddata",
                    ),
                ),
                ("operations", models.ManyToManyField(to="proc.operation")),
                (
                    "sps_pkg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="package.spspkg",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["operation_name"], name="proc_operat_operati_214493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalproc",
            index=models.Index(fields=["acron"], name="proc_journa_acron_877d44_idx"),
        ),
        migrations.AddIndex(
            model_name="issueproc",
            index=models.Index(
                fields=["issue_folder"], name="proc_issuep_issue_f_c0f33b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueproc",
            index=models.Index(
                fields=["docs_status"], name="proc_issuep_docs_st_e5964c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueproc",
            index=models.Index(
                fields=["files_status"], name="proc_issuep_files_s_a42fed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["pkg_name"], name="proc_articl_pkg_nam_3a7648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["xml_status"], name="proc_articl_xml_sta_59938e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["sps_pkg_status"], name="proc_articl_sps_pkg_7629ac_idx"
            ),
        ),
    ]
