# Generated by Django 4.2.6 on 2024-01-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0002_alter_migrateddata_migration_status"),
        ("proc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleproc",
            name="file",
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="migrated_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="migration.migratedarticle",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="public_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Public Website Status",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="qa_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="QA Website Status",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="sps_pkg_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                null=True,
                verbose_name="SPS Pkg status",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="xml_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                null=True,
                verbose_name="XML status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="docs_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Document records migration status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="files_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Files migration status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="migrated_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="migration.migratedissue",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="public_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Public Website Status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="qa_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="QA Website Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="migrated_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="migration.migratedjournal",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="public_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Public Website Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="qa_ws_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="QA Website Status",
            ),
        ),
    ]
