# Generated by Django 4.2.6 on 2024-01-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleproc",
            name="zip_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                null=True,
                verbose_name="Zip status",
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["zip_status"], name="proc_articl_zip_sta_6fe6e2_idx"
            ),
        ),
    ]
