# Generated by Django 5.0.3 on 2024-03-28 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0002_remove_websiteconfiguration_api_token_and_more"),
        ("proc", "0002_procreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procreport",
            name="item_type",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Item type"
            ),
        ),
        migrations.AddIndex(
            model_name="procreport",
            index=models.Index(
                fields=["item_type"], name="proc_procre_item_ty_0b33db_idx"
            ),
        ),
    ]
