# Generated by Django 5.0.3 on 2024-04-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0004_alter_articleproc_options_alter_issueproc_options_and_more"),
        ("upload", "0003_package_journal_alter_errorresolution_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleproc",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="upload.package",
            ),
        ),
    ]
