# Generated by Django 5.0.3 on 2024-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0004_alter_articleproc_options_alter_issueproc_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procreport",
            name="task_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Procedure name"
            ),
        ),
    ]
