# Generated by Django 5.0.3 on 2024-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0005_alter_procreport_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueproc",
            name="resumption_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
