# Generated by Django 5.0.3 on 2024-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0006_issueproc_resumption_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="event",
        ),
    ]
