# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0007_remove_operation_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Migration Status",
            ),
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Package name"
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Migration Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Migration Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title"
            ),
        ),
    ]
