# Generated by Django 5.0.3 on 2025-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0008_alter_articleproc_migration_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issueproc",
            name="resumption_date",
        ),
        migrations.AlterField(
            model_name="articleproc",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Package name"
            ),
        ),
    ]
