# Generated by Django 5.0.3 on 2025-05-17 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0008_alter_articleproc_migration_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issueproc",
            name="resumption_date",
        ),
    ]
