# Generated by Django 5.0.3 on 2025-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0009_remove_issueproc_resumption_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleproc",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Package name"
            ),
        ),
    ]
