# Generated by Django 5.2.3 on 2025-11-11 13:56

import proc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0009_remove_issueproc_resumption_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleproc",
            name="processed_xml",
            field=models.FileField(
                blank=True,
                help_text="Native XML + modifications or converted XML from HTML",
                null=True,
                upload_to=proc.models.proc_directory_path,
                verbose_name="Processed XML",
            ),
        ),
    ]
