# Generated by Django 5.2.3 on 2026-01-14 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0010_articleproc_processed_xml"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={"ordering": ["-updated"]},
        ),
    ]
