# Generated by Django 5.2.3 on 2026-02-11 18:16

import proc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0011_alter_operation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleproc",
            name="processed_xml",
            field=models.FileField(
                blank=True,
                help_text="Native XML + modifications or converted XML from HTML",
                max_length=300,
                null=True,
                upload_to=proc.models.proc_directory_path,
                verbose_name="Processed XML",
            ),
        ),
        migrations.AlterField(
            model_name="procreport",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=proc.models.proc_report_directory_path,
            ),
        ),
    ]
