# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0012_alter_articleproc_processed_xml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleproc",
            name="pid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("missing", "Missing"),
                    ("matched", "Matched"),
                    ("exceeding", "Exceeding"),
                ],
                default="",
                max_length=10,
                verbose_name="PID Status",
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["pid_status"], name="proc_articl_pid_sta_idx"
            ),
        ),
    ]
