# Generated by Django 5.2.3 on 2026-03-18 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
        ("migration", "0011_alter_journalacronidfile_file_and_more"),
        ("package", "0007_delete_previewarticlepage"),
        ("proc", "0012_alter_articleproc_processed_xml_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articleproc",
            name="pid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing", "Missing"),
                    ("matched", "Matched"),
                    ("exceeding", "Exceeding"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
                null=True,
                verbose_name="PID Status",
            ),
        ),
        migrations.AddIndex(
            model_name="articleproc",
            index=models.Index(
                fields=["pid_status"], name="proc_articl_pid_sta_604d39_idx"
            ),
        ),
    ]
