# Generated by Django 5.2.3 on 2026-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0013_articleproc_pid_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleproc",
            name="pid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing", "Missing"),
                    ("matched", "Matched"),
                    ("exceeding", "Exceeding"),
                    ("unknown", "Unknown"),
                    ("published", "Published"),
                    ("public_nfound", "Published but not found"),
                    ("public_ok", "Published and content valid"),
                    ("public_nok", "Published and mismatched content"),
                    ("classic_ok", "Classic and matched content"),
                    ("classic_nok", "Classic and mismatched content"),
                    ("classic_found", "Classic found"),
                    ("classic_nfound", "Classic not found"),
                ],
                default="unknown",
                max_length=14,
                null=True,
                verbose_name="PID Status",
            ),
        ),
    ]
