# Generated by Django 5.2.3 on 2026-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proc", "0014_alter_articleproc_pid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Registration Status",
            ),
        ),
        migrations.AlterField(
            model_name="issueproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Registration Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalproc",
            name="migration_status",
            field=models.CharField(
                choices=[
                    ("REPROC", "To reprocess"),
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("DOING", "Doing"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("IGNORED", "ignored"),
                ],
                default="TODO",
                max_length=8,
                verbose_name="Registration Status",
            ),
        ),
    ]
