# Generated by Django 3.2.12 on 2022-12-31 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v3')),
                ('xml_uri', models.CharField(blank=True, max_length=256, null=True, verbose_name='XML URI')),
                ('status', models.CharField(blank=True, choices=[('WAITING_FOR_QA', 'WAITING_FOR_QA'), ('QA', 'QA'), ('SCHEDULED_TO_PUBLISH', 'SCHEDULED_TO_PUBLISH'), ('PUBLISHED', 'PUBLISHED')], max_length=20, null=True, verbose_name='Publication status')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publicationarticle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicationarticle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
