# Generated by Django 5.0.3 on 2025-02-28 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0002_collectionverificationfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CollectionVerificationFile",
        ),
    ]
