# Generated by Django 5.0.3 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0003_delete_collectionverificationfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleavailability",
            options={
                "verbose_name": "Article availability",
                "verbose_name_plural": "Article availability",
            },
        ),
        migrations.AddField(
            model_name="articleavailability",
            name="publication_rule",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="publication rule"
            ),
        ),
        migrations.AddField(
            model_name="articleavailability",
            name="published_by",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="published by"
            ),
        ),
        migrations.AddField(
            model_name="articleavailability",
            name="published_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="0-100",
                max_digits=5,
                verbose_name="Published percentual",
            ),
        ),
    ]
