# Generated by Django 5.0.3 on 2025-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0003_delete_collectionverificationfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleavailability",
            name="publication_rule",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="publication rule"
            ),
        ),
        migrations.AddField(
            model_name="articleavailability",
            name="published_by",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="published by"
            ),
        ),
    ]
