# Generated by Django 5.0.3 on 2025-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0004_articleavailability_publication_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleavailability",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
