# Generated by Django 5.0.8 on 2025-06-26 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0004_articleavailability_publication_rule_and_more"),
        ("publication", "0005_alter_articleavailability_options_and_more"),
    ]

    operations = []
