# Generated by Django 5.2.3 on 2025-12-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0007_alter_article_options_article_first_pubdate_iso"),
        ("publication", "0005_alter_articleavailability_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleavailability",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availability_status",
                to="article.article",
                unique=True,
            ),
        ),
    ]
