# Generated by Django 3.2.12 on 2022-08-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Submetido'), ('2', 'Enqueued for validation'), ('3', 'Validated with errors'), ('4', 'Validated without errors'), ('5', 'Rejeitado'), ('6', 'Accepted'), ('7', 'Scheduled for publication'), ('8', 'Publicado')], default='1', verbose_name='Status'),
        ),
    ]
