# Generated by Django 3.2.12 on 2022-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetido'), ('enqueued-for-validation', 'Enqueued for validation'), ('validated-with-errors', 'Validated with errors'), ('validated-without-errors', 'Validated without errors'), ('pending-correction', 'Pending for correction'), ('ready-to-be-finished', 'Ready to be finished'), ('quality-analysis', 'Waiting for quality analysis'), ('rejected', 'Rejeitado'), ('accepted', 'Accepted'), ('scheduled-for-publication', 'Scheduled for publication'), ('published', 'Publicado')], default='enqueued-for-validation', max_length=32, verbose_name='Status'),
        ),
    ]
