# Generated by Django 3.2.12 on 2022-09-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220912_2247'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetido'), ('enqueued-for-validation', 'Enqueued for validation'), ('validated-with-errors', 'Validated with errors'), ('validated-without-errors', 'Validated without errors'), ('pending-correction', 'Pending for correction'), ('ready-to-be-finished', 'Ready to be finished'), ('quality-analysis', 'Waiting for quality analysis'), ('rejected', 'Rejeitado'), ('accepted', 'Accepted'), ('scheduled-for-publication', 'Scheduled for publication'), ('published', 'Publicado'), ('required-erratum', 'Required erratum'), ('required-update', 'Required update')], default='enqueued-for-validation', max_length=32, verbose_name='Status'),
        ),
    ]
