# Generated by Django 4.2.6 on 2024-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationresult",
            name="category",
            field=models.CharField(
                choices=[
                    ("unexpected-error", "UNEXPECTED_ERROR"),
                    ("forbidden-update-error", "FORBIDDEN_UPDATE_ERROR"),
                    (
                        "article-journal-incompatibility-error",
                        "ARTICLE_JOURNAL_INCOMPATIBILITY_ERROR",
                    ),
                    ("article-is-not-new-error", "ARTICLE_IS_NOT_NEW_ERROR"),
                    ("xml-format-error", "XML_FORMAT_ERROR"),
                    ("bibliometrics-data-error", "BIBLIOMETRICS_DATA_ERROR"),
                    ("services-data-error", "SERVICES_DATA_ERROR"),
                    ("data-consistency-error", "DATA_CONSISTENCY_ERROR"),
                    ("criteria-issues-error", "CRITERIA_ISSUES"),
                    ("asset-error", "ASSET_ERROR"),
                    ("rendition-error", "RENDITION_ERROR"),
                ],
                max_length=64,
                verbose_name="Error category",
            ),
        ),
    ]
