# Generated by Django 5.0.3 on 2024-10-10 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_remove_articleauthor_author_and_more"),
        ("issue", "0004_issue_issue_pid_suffix_issue_order_toc_tocsection"),
        ("journal", "0005_journaltoc_alter_journal_official_journal_and_more"),
        ("package", "0003_remove_spspkg_components_remove_spspkg_scheduled_and_more"),
        ("team", "0001_initial"),
        ("upload", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="main_doi",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="DOI"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["main_doi"], name="upload_pack_main_do_8da804_idx"
            ),
        ),
    ]
