# Generated by Django 3.2.12 on 2022-08-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_package_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assets', 'Assets'), ('stylesheet', 'Stylesheet'), ('structure', 'Structure'), ('individual-content', 'Individual content'), ('group content', 'Group content')], max_length=128, verbose_name='Category')),
                ('severity', models.CharField(choices=[('criteria-issues', 'Criteria issues'), ('warning', 'Warning'), ('error', 'Erro'), ('fatal-error', 'Fatal error'), ('blocking-error', 'Blocking error')], max_length=128, verbose_name='Severity')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Position')),
                ('snippet', models.TextField(blank=True, max_length=10240, null=True, verbose_name='Affected snippet')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.package')),
            ],
        ),
    ]
