# Generated by Django 5.0.3 on 2024-08-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_basexmlvalidationresult_pkgvalidationresult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="approved_date",
        ),
        migrations.RemoveField(
            model_name="package",
            name="website_pub_date",
        ),
        migrations.RemoveField(
            model_name="package",
            name="xml_pub_date",
        ),
        migrations.AddField(
            model_name="package",
            name="qa_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Quality analysis comment"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="qa_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending-correction", "Pending for correction"),
                    ("ready-to-preview", "Ready to preview"),
                    ("ready-to-publish", "Ready to publish"),
                ],
                max_length=32,
                null=True,
                verbose_name="Quality analysis decision",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("required-erratum", "Required erratum"),
                    ("required-update", "Required update"),
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("pending-correction", "Pending for correction"),
                    ("unexpected", "Unexpected"),
                    ("ready-to-preview", "Ready to preview"),
                    ("preview", "Pré-visualizar"),
                    ("scheduled-publication", "Scheduled publication"),
                    ("ready-to-publish", "Ready to publish"),
                    ("published", "Publicado"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="uploadvalidator",
            name="decision_for_blocking_errors",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending-correction", "Pending for correction"),
                    ("validated-with-errors", "Validated with errors"),
                ],
                default="validated-with-errors",
                max_length=32,
                null=True,
            ),
        ),
    ]
