# Generated by Django 5.0.3 on 2024-10-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
        ("upload", "0002_package_main_doi_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": (
                    ("finish_deposit", "Can finish deposit"),
                    ("access_all_packages", "Can access all packages from all users"),
                    ("assign_package", "Can assign package"),
                ),
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.AlterModelOptions(
            name="packagezip",
            options={"verbose_name": "Zip file", "verbose_name_plural": "Zip files"},
        ),
        migrations.AlterModelOptions(
            name="qapackage",
            options={
                "verbose_name": "Pending decision package",
                "verbose_name_plural": "Pending decision packages",
            },
        ),
        migrations.AlterModelOptions(
            name="readytopublishpackage",
            options={
                "verbose_name": "Package ready to publish",
                "verbose_name_plural": "Packages ready to publish",
            },
        ),
        migrations.AddField(
            model_name="packagezip",
            name="show_package_validations",
            field=models.BooleanField(
                default=False,
                help_text="Unchecked to be redirect to package upload. Checked to be redirect to package validation",
                verbose_name="Show package validations",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="analyst",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the analyst who will decide about the package or add your decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.collectionteammember",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="qa_comment",
            field=models.TextField(
                blank=True,
                help_text="Comment the decision about the package or choose the analyst who will comment it",
                null=True,
                verbose_name="Quality analysis comment",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="qa_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("depublished", "Depublish"),
                    ("pending-correction", "Pending for correction"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("ready-to-preview", "Ready to preview on QA website"),
                    ("ready-to-publish", "Ready to publish on public website"),
                ],
                help_text="Make a decision about the package or choose the analyst who will decide it",
                max_length=32,
                null=True,
                verbose_name="Quality analysis decision",
            ),
        ),
    ]
