# Generated by Django 3.2.12 on 2022-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20220825_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'permissions': (('finish_deposit', 'Can finish deposit'), ('access_all_packages', 'Can access all packages from all users'))},
        ),
        migrations.AlterField(
            model_name='errorresolution',
            name='action',
            field=models.CharField(blank=True, choices=[('to-fix', 'I will fix this error'), ('disagree', 'This is not an error'), ('unknown', 'I do not know how to fix this error')], max_length=32, null=True, verbose_name='Action'),
        ),
    ]
