# Generated by Django 3.2.12 on 2022-08-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_package_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assets', 'Assets'), ('stylesheet', 'Stylesheet'), ('structure', 'Structure'), ('individual-content', 'Individual content'), ('group-content', 'Group content')], max_length=128, verbose_name='Category')),
                ('severity', models.CharField(choices=[('criteria-issues', 'CRITERIA_ISSUES'), ('warning', 'WARNING'), ('error', 'ERROR'), ('bibliometrics-data-error', 'BIBLIOMETRICS_DATA_ERROR'), ('services-data-error', 'SERVICES_DATA_ERROR'), ('data-consistency-error', 'DATA_CONSISTENCY_ERROR'), ('xml-format-error', 'XML_FORMAT_ERROR')], max_length=128, verbose_name='Severity')),
                ('row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Row')),
                ('column', models.PositiveIntegerField(blank=True, null=True, verbose_name='Column')),
                ('snippet', models.TextField(blank=True, max_length=255, null=True, verbose_name='Affected snippet')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.package')),
            ],
        ),
    ]
