# Generated by Django 5.0.3 on 2024-04-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_remove_owner_page_remove_publisher_page_and_more"),
        ("upload", "0002_alter_validationresult_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="errorresolution",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("to-fix", "I will fix this error"),
                    ("disagree", "This is not an error"),
                ],
                default="to-fix",
                max_length=32,
                null=True,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="validationresult",
            name="category",
            field=models.CharField(
                choices=[
                    ("unexpected-error", "UNEXPECTED_ERROR"),
                    ("forbidden-update-error", "FORBIDDEN_UPDATE_ERROR"),
                    (
                        "journal-incompatibility-error",
                        "ARTICLE_JOURNAL_INCOMPATIBILITY_ERROR",
                    ),
                    ("article-is-not-new-error", "ARTICLE_IS_NOT_NEW_ERROR"),
                    ("xml-format-error", "XML_FORMAT_ERROR"),
                    ("xml-content-error", "VE_XML_CONTENT_ERROR"),
                    ("group-error", "VE_GROUP_DATA_ERROR"),
                    ("bibliometrics-data-error", "BIBLIOMETRICS_DATA_ERROR"),
                    ("services-data-error", "SERVICES_DATA_ERROR"),
                    ("data-consistency-error", "DATA_CONSISTENCY_ERROR"),
                    ("criteria-issues-error", "CRITERIA_ISSUES"),
                    ("asset-error", "ASSET_ERROR"),
                    ("rendition-error", "RENDITION_ERROR"),
                ],
                max_length=32,
                verbose_name="Error category",
            ),
        ),
    ]
