# Generated by Django 5.0.3 on 2024-05-08 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "upload",
            "0003_basexmlvalidationresult_package_journal_package_name_and_more",
        ),
        ("upload", "0003_package_journal_alter_errorresolution_action_and_more"),
    ]

    operations = []
