# Generated by Django 5.0.3 on 2024-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0003_alter_package_options_alter_packagezip_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedPackage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("upload.package",),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("required-erratum", "Required erratum"),
                    ("required-update", "Required update"),
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("pending-correction", "Pending for correction"),
                    ("unexpected", "Unexpected"),
                    ("ready-to-preview", "Ready to preview on QA website"),
                    ("preview", "Pré-visualizar"),
                    ("ready-to-publish", "Ready to publish on public website"),
                    ("published", "Publicado"),
                    ("archived", "Archived"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                    ("package-file", "PACKAGE_FILE"),
                    ("qa-conclusion", "QA conclusion"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                    ("package-file", "PACKAGE_FILE"),
                    ("qa-conclusion", "QA conclusion"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                    ("package-file", "PACKAGE_FILE"),
                    ("qa-conclusion", "QA conclusion"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
    ]
