# Generated by Django 3.2.12 on 2022-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20220826_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAPackage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('upload.package',),
        ),
    ]
