# Generated by Django 5.0.3 on 2024-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0004_archivedpackage_alter_package_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="SPS Package name"
            ),
        ),
        migrations.AlterField(
            model_name="xmlerror",
            name="reaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("to-fix", "The error will be fixed"),
                    ("unable-to-fix", "Impossible to fix it"),
                    ("not-to-fix", "There's disagreement about the error"),
                ],
                default="to-fix",
                max_length=16,
                null=True,
                verbose_name="Reaction",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="xml_producer_ack",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="The error review is complete",
            ),
        ),
    ]
