# Generated by Django 5.0.3 on 2025-03-02 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_alter_package_name_alter_xmlerror_reaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": (
                    ("finish_deposit", "Can finish deposit"),
                    ("access_all_packages", "Can access all packages from all users"),
                    ("assign_package", "Can assign package"),
                ),
                "verbose_name": "Package admin",
                "verbose_name_plural": "Package admin",
            },
        ),
        migrations.AlterModelOptions(
            name="qapackage",
            options={
                "verbose_name": "Quality control admin",
                "verbose_name_plural": "Quality control admin",
            },
        ),
        migrations.AlterModelOptions(
            name="readytopublishpackage",
            options={
                "verbose_name": "Publication admin",
                "verbose_name_plural": "Publication admin",
            },
        ),
    ]
