# Generated by Django 5.0.3 on 2025-04-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0006_alter_package_options_alter_qapackage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvalidator",
            name="validation_params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="message",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Message"
            ),
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="parent",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="article / sub-article",
            ),
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="parent_id",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="@id"
            ),
        ),
        migrations.AlterField(
            model_name="pkgvalidationresult",
            name="message",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Message"
            ),
        ),
        migrations.AlterField(
            model_name="xmlerror",
            name="advice",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Advice"
            ),
        ),
    ]
