# Generated by Django 5.0.3 on 2025-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0007_uploadvalidator_validation_params_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="qa_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("depublished", "Depublish"),
                    ("pending-correction", "Request correction"),
                    ("pending-qa-decision", "Assign quality review"),
                    ("ready-to-preview", "Publish on QA website"),
                    ("ready-to-publish", "Publish on public website"),
                ],
                help_text="Make a decision about the package or choose the analyst who will decide it",
                max_length=32,
                null=True,
                verbose_name="Quality analysis decision",
            ),
        ),
    ]
