# Generated by Django 5.0.8 on 2025-08-21 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_article_pp_xml"),
        ("issue", "0004_issue_issue_pid_suffix_issue_order_toc_tocsection"),
        ("journal", "0013_delete_journaltoc_alter_journalsection_parent"),
        ("package", "0006_alter_spspkg_sps_pkg_name"),
        ("team", "0001_initial"),
        ("upload", "0008_alter_package_qa_decision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="blocking_errors",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["blocking_errors"], name="upload_pack_blockin_39ecda_idx"
            ),
        ),
    ]
