# Generated by Django 5.0.8 on 2025-08-26 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_article_pp_xml"),
        ("issue", "0004_issue_issue_pid_suffix_issue_order_toc_tocsection"),
        ("package", "0006_alter_spspkg_sps_pkg_name"),
        ("team", "0001_initial"),
        ("upload", "0008_alter_package_qa_decision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PidReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pkg_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Package name",
                    ),
                ),
                (
                    "pid_v2",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="PID v2"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pid Reservation",
                "verbose_name_plural": "Pid Reservations",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="blocking_errors",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["blocking_errors"], name="upload_pack_blockin_39ecda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidreservation",
            index=models.Index(
                fields=["pkg_name"], name="upload_pidr_pkg_nam_645b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidreservation",
            index=models.Index(fields=["pid_v2"], name="upload_pidr_pid_v2_510ceb_idx"),
        ),
    ]
