# Generated by Django 5.2.3 on 2025-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0009_pidreservation_package_blocking_errors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("update", "Update"),
                    ("erratum", "Erratum"),
                    ("new-document", "New document"),
                ],
                max_length=32,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("required-erratum", "Required erratum"),
                    ("required-update", "Required update"),
                    ("submitted", "Submitted"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("pending-correction", "Pending for correction"),
                    ("unexpected", "Unexpected"),
                    ("ready-to-preview", "Ready to preview on QA website"),
                    ("preview", "Preview"),
                    ("ready-to-publish", "Ready to publish on public website"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
