# Generated by Django 5.2.3

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0010_alter_package_category_alter_package_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlerrorreport",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=upload.models.upload_package_directory_path,
                verbose_name="Report File",
            ),
        ),
    ]
