# Generated by Django 5.2.7 on 2026-08-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0010_alter_package_category_alter_package_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": (
                    ("finish_deposit", "Can finish deposit"),
                    ("access_all_packages", "Can access all packages from all users"),
                    ("assign_package", "Can assign package"),
                    ("publish_package", "Can publish package"),
                    ("republish_package", "Can republish package"),
                ),
                "verbose_name": "Package admin",
                "verbose_name_plural": "Package admin",
            },
        ),
    ]
