# Generated by Django 3.2.19 on 2023-06-30 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xmlsps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLSPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('file', models.FileField(blank=True, null=True, upload_to=xmlsps.models.xml_directory_path)),
                ('uri', models.URLField(blank=True, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='xmlsps_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xmlsps_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'XML SPS',
                'verbose_name_plural': 'XML SPS',
                'ordering': ('file',),
            },
        ),
    ]
