# Generated by Django 5.2.3 on 2025-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Name"),
        ),
    ]
