# Generated by Django 3.2.12 on 2022-12-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v3', models.CharField(max_length=23, null=True, verbose_name='v3')),
                ('main_doi', models.CharField(max_length=265, null=True, verbose_name='main_doi')),
                ('elocation_id', models.CharField(max_length=23, null=True, verbose_name='elocation_id')),
                ('article_titles_texts', models.CharField(max_length=64, null=True, verbose_name='article_titles_texts')),
                ('surnames', models.CharField(max_length=64, null=True, verbose_name='surnames')),
                ('collab', models.CharField(max_length=64, null=True, verbose_name='collab')),
                ('links', models.CharField(max_length=64, null=True, verbose_name='links')),
                ('partial_body', models.CharField(max_length=64, null=True, verbose_name='partial_body')),
            ],
        ),
        migrations.CreateModel(
            name='RequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('xml_source', models.CharField(max_length=255, null=True, verbose_name='XML source')),
                ('v3', models.CharField(max_length=23, null=True, verbose_name='v3')),
                ('error_msg', models.CharField(max_length=255, null=True, verbose_name='error_msg')),
                ('error_type', models.CharField(max_length=255, null=True, verbose_name='error_type')),
            ],
        ),
        migrations.CreateModel(
            name='XMLIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=10, null=True, verbose_name='volume')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='number')),
                ('suppl', models.CharField(max_length=10, null=True, verbose_name='suppl')),
                ('pub_year', models.IntegerField(verbose_name='pub_year')),
            ],
        ),
        migrations.CreateModel(
            name='XMLJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn_electronic', models.CharField(max_length=9, null=True, verbose_name='issn_epub')),
                ('issn_print', models.CharField(max_length=9, null=True, verbose_name='issn_ppub')),
            ],
        ),
        migrations.CreateModel(
            name='XMLAOPArticle',
            fields=[
                ('basearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pid_provider.basearticle')),
                ('aop_pid', models.CharField(max_length=23, null=True, verbose_name='aop_pid')),
            ],
            bases=('pid_provider.basearticle',),
        ),
        migrations.CreateModel(
            name='XMLArticle',
            fields=[
                ('basearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pid_provider.basearticle')),
                ('v2', models.CharField(max_length=23, null=True, verbose_name='v2')),
                ('fpage', models.CharField(max_length=10, null=True, verbose_name='fpage')),
                ('fpage_seq', models.CharField(max_length=10, null=True, verbose_name='fpage_seq')),
                ('lpage', models.CharField(max_length=10, null=True, verbose_name='lpage')),
            ],
            bases=('pid_provider.basearticle',),
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_electronic'], name='pid_provide_issn_el_3663e3_idx'),
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_print'], name='pid_provide_issn_pr_37880c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmljournal',
            unique_together={('issn_electronic', 'issn_print')},
        ),
        migrations.AddField(
            model_name='xmlissue',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmljournal'),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requestresult_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestresult_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='basearticle',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='basearticle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='basearticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basearticle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='basearticle',
            name='versions',
            field=models.ManyToManyField(to='files_storage.MinioFile'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['journal'], name='pid_provide_journal_08103a_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['volume'], name='pid_provide_volume_f39ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['number'], name='pid_provide_number_f36ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['suppl'], name='pid_provide_suppl_241841_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['pub_year'], name='pid_provide_pub_yea_bcd879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmlissue',
            unique_together={('journal', 'pub_year', 'volume', 'number', 'suppl')},
        ),
        migrations.AddField(
            model_name='xmlarticle',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmlissue'),
        ),
        migrations.AddField(
            model_name='xmlaoparticle',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmljournal'),
        ),
        migrations.AddField(
            model_name='xmlaoparticle',
            name='published_in_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmlarticle'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['v3'], name='pid_provide_v3_687543_idx'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['xml_source'], name='pid_provide_xml_sou_e23c29_idx'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['created'], name='pid_provide_created_a7d9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['updated_by'], name='pid_provide_updated_81f486_idx'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['error_type'], name='pid_provide_error_t_1f5007_idx'),
        ),
        migrations.AddIndex(
            model_name='requestresult',
            index=models.Index(fields=['error_msg'], name='pid_provide_error_m_1be7de_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['v3'], name='pid_provide_v3_7e6bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['main_doi'], name='pid_provide_main_do_3fb8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['article_titles_texts'], name='pid_provide_article_70007e_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['surnames'], name='pid_provide_surname_c2df4c_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['collab'], name='pid_provide_collab_33f762_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['links'], name='pid_provide_links_b28685_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['partial_body'], name='pid_provide_partial_06fb11_idx'),
        ),
        migrations.AddIndex(
            model_name='basearticle',
            index=models.Index(fields=['elocation_id'], name='pid_provide_elocati_8f3fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['v2'], name='pid_provide_v2_0058dc_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['issue'], name='pid_provide_issue_i_dedcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['fpage'], name='pid_provide_fpage_8cecfe_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['fpage_seq'], name='pid_provide_fpage_s_1bc740_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['lpage'], name='pid_provide_lpage_daa600_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlaoparticle',
            index=models.Index(fields=['journal'], name='pid_provide_journal_e8f41a_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlaoparticle',
            index=models.Index(fields=['aop_pid'], name='pid_provide_aop_pid_79191e_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlaoparticle',
            index=models.Index(fields=['published_in_issue'], name='pid_provide_publish_8bbf53_idx'),
        ),
    ]
