# Generated by Django 4.2.6 on 2024-03-22 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pidproviderxml",
            options={"ordering": ["-updated", "-created", "pkg_name"]},
        ),
        migrations.CreateModel(
            name="FixPidV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "incorrect_pid_v2",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Incorrect v2",
                    ),
                ),
                (
                    "correct_pid_v2",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="Correct v2"
                    ),
                ),
                (
                    "fixed_in_upload",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fixed_in_core",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "pid_provider_xml",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pid_provider.pidproviderxml",
                        unique=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
                "indexes": [
                    models.Index(
                        fields=["incorrect_pid_v2"],
                        name="pid_provide_incorre_17a11a_idx",
                    ),
                    models.Index(
                        fields=["correct_pid_v2"], name="pid_provide_correct_ac149d_idx"
                    ),
                    models.Index(
                        fields=["fixed_in_core"], name="pid_provide_fixed_i_4e3bd1_idx"
                    ),
                    models.Index(
                        fields=["fixed_in_upload"],
                        name="pid_provide_fixed_i_0109bc_idx",
                    ),
                ],
            },
        ),
    ]
