# Generated by Django 3.2.12 on 2022-12-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0003_auto_20221231_0214'),
        ('pid_provider', '0003_delete_requestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basearticle',
            name='versions',
        ),
        migrations.AddField(
            model_name='basearticle',
            name='versions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_storage.fileversions'),
        ),
    ]
