# Generated by Django 3.2.12 on 2022-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0004_remove_fileversions_versions'),
        ('pid_provider', '0004_auto_20221231_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basearticle',
            name='versions',
        ),
        migrations.AddField(
            model_name='basearticle',
            name='versions',
            field=models.ManyToManyField(to='files_storage.MinioFile'),
        ),
    ]
