# Generated by Django 5.2.3 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
        ("pid_provider", "0005_remove_pidproviderendpoint_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pidrequest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="pidrequest",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="collections",
            field=models.ManyToManyField(blank=True, to="collection.collection"),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_electronic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Electronic ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_print",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Print ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="proc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("WAIT", "waiting"),
                    ("IGNORE", "ignore"),
                    ("UNDEF", "undefined"),
                    ("NVALID", "invalid"),
                ],
                default="TODO",
                max_length=7,
                null=True,
                verbose_name="processing status",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="pub_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="publication year"
            ),
        ),
        migrations.DeleteModel(
            name="CollectionPidRequest",
        ),
        migrations.DeleteModel(
            name="PidRequest",
        ),
    ]
