# Generated by Django 5.2.3 on 2026-02-09 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0008_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="XMLURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Article PID",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "XML URL",
                "verbose_name_plural": "XML URLs",
                "ordering": ["-updated", "-created"],
                "indexes": [
                    models.Index(
                        fields=["url"],
                        name="pid_provide_url_idx",
                    ),
                    models.Index(
                        fields=["status"],
                        name="pid_provide_status_idx",
                    ),
                    models.Index(
                        fields=["pid"],
                        name="pid_provide_pid_idx",
                    ),
                ],
            },
        ),
    ]
