# Generated by Django 5.2.3 on 2026-02-09 23:13

import pid_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0009_xmlurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlurl",
            name="zipfile",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pid_provider.models.xml_url_zipfile_path,
                verbose_name="ZIP File",
            ),
        ),
    ]
