# Generated by Django 5.2.3 on 2026-02-11 18:16

import pid_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0009_xmlurl"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="xmlurl",
            new_name="pid_provide_url_d6fff2_idx",
            old_name="pid_provide_url_idx",
        ),
        migrations.RenameIndex(
            model_name="xmlurl",
            new_name="pid_provide_status_39bead_idx",
            old_name="pid_provide_status_idx",
        ),
        migrations.RenameIndex(
            model_name="xmlurl",
            new_name="pid_provide_pid_588ddc_idx",
            old_name="pid_provide_pid_idx",
        ),
        migrations.AlterField(
            model_name="xmlurl",
            name="zipfile",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=pid_provider.models.xml_url_zipfile_path,
                verbose_name="ZIP File",
            ),
        ),
        migrations.AlterField(
            model_name="xmlversion",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=pid_provider.models.xml_directory_path,
            ),
        ),
    ]
