# Generated by Django 5.2.3 on 2026-02-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0010_xmlurl_zipfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlurl",
            name="exceptions",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Exceptions",
            ),
        ),
    ]
