# Generated by Django 5.2.3 on 2026-06-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pid_provider",
            "0010_rename_pid_provide_url_idx_pid_provide_url_d6fff2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlurl",
            name="detail",
            field=models.JSONField(blank=True, null=True, verbose_name="Detail"),
        ),
    ]
