# Generated by Django 5.2.3 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pid_provider",
            "0011_xmlurl_detail_alter_xmlurl_exceptions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlurl",
            name="is_public",
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name="Is Public"),
        ),
        migrations.AddIndex(
            model_name="xmlurl",
            index=models.Index(fields=["is_public"], name="pid_provide_is_public_idx"),
        ),
    ]
