# Generated by Django 5.2.3 on 2026-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0012_xmlurl_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmlurl",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("xml_fetch_failed", "XML fetch failed"),
                    ("pid_provider_xml_failed", "PID provider XML failed"),
                ],
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
