# Generated by Django 5.2.3 on 2026-06-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0013_alter_xmlurl_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pidproviderxml",
            name="readable_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Readable data"),
        ),
        migrations.CreateModel(
            name="PidProviderXMLRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pkg_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Package name",
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "created"),
                            ("updated", "updated"),
                            ("skipped", "skipped"),
                            ("forbidden", "forbidden"),
                            ("conflict", "conflict"),
                            ("unmatched", "unmatched"),
                            ("bad_request", "bad_request"),
                            ("error", "error"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Event status",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Input data (readable)"
                    ),
                ),
                (
                    "best_matches",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Best matches detail"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Error type"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "pid_provider_xml",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_events",
                        to="pid_provider.pidproviderxml",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "PidProviderXML Registration",
                "verbose_name_plural": "PidProviderXML Registrations",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["pkg_name"], name="pid_provide_pkg_nam_2db0b2_idx"
                    ),
                    models.Index(
                        fields=["event_status"], name="pid_provide_event_s_3c9ae7_idx"
                    ),
                    models.Index(
                        fields=["-created"], name="pid_provide_created_94fb08_idx"
                    ),
                    models.Index(
                        fields=["pid_provider_xml"],
                        name="pid_provide_pid_pro_c9fb0e_idx",
                    ),
                ],
            },
        ),
    ]
