# Generated by Django 3.2.12 on 2022-12-23 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('source_filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('uri', models.URLField(blank=True, max_length=255, null=True, verbose_name='URI')),
                ('finger_print', models.CharField(blank=True, max_length=64, null=True, verbose_name='Finger print')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='miniofile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miniofile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host')),
                ('bucket_root', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bucket root')),
                ('bucket_app_subdir', models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket app subdir')),
                ('access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access key')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret key')),
                ('secure', models.BooleanField(default=True, verbose_name='Secure')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['source_filename'], name='files_stora_source__64b382_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['creator'], name='files_stora_creator_fefb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['updated_by'], name='files_stora_updated_a6297c_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['finger_print'], name='files_stora_finger__d77bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['name'], name='files_stora_name_347d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['host'], name='files_stora_host_308b41_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['bucket_root'], name='files_stora_bucket__4977ac_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['bucket_app_subdir'], name='files_stora_bucket__ce3147_idx'),
        ),
    ]
