# Generated by Django 4.1.10 on 2023-08-27 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "basename",
                    models.TextField(blank=True, null=True, verbose_name="Basename"),
                ),
                ("uri", models.URLField(blank=True, null=True, verbose_name="URI")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteSPSPkg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                ("locations", models.ManyToManyField(to="files_storage.filelocation")),
                (
                    "sps_pkg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="package.spspkg",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinioConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.TextField(null=True, verbose_name="Name")),
                ("host", models.TextField(blank=True, null=True, verbose_name="Host")),
                (
                    "bucket_root",
                    models.TextField(blank=True, null=True, verbose_name="Bucket root"),
                ),
                (
                    "bucket_app_subdir",
                    models.TextField(
                        blank=True, null=True, verbose_name="Bucket app subdir"
                    ),
                ),
                (
                    "access_key",
                    models.TextField(blank=True, null=True, verbose_name="Access key"),
                ),
                (
                    "secret_key",
                    models.TextField(blank=True, null=True, verbose_name="Secret key"),
                ),
                ("secure", models.BooleanField(default=True, verbose_name="Secure")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="minioconfiguration",
            index=models.Index(fields=["name"], name="files_stora_name_6664a8_idx"),
        ),
        migrations.AddIndex(
            model_name="minioconfiguration",
            index=models.Index(fields=["host"], name="files_stora_host_12e098_idx"),
        ),
        migrations.AddIndex(
            model_name="minioconfiguration",
            index=models.Index(
                fields=["bucket_root"], name="files_stora_bucket__8a0a27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filelocation",
            index=models.Index(
                fields=["basename"], name="files_stora_basenam_bdbd84_idx"
            ),
        ),
    ]
