# Generated by Django 5.0.3 on 2025-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files_storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filelocation",
            name="basename",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Basename"
            ),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="access_key",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Access key"
            ),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="bucket_app_subdir",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Bucket app subdir"
            ),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="bucket_root",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Bucket root"
            ),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="host",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Host"
            ),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="name",
            field=models.CharField(max_length=32, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="minioconfiguration",
            name="secret_key",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Secret key"
            ),
        ),
    ]
