# Generated by Django 3.2.12 on 2022-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='miniofile',
            name='files_stora_source__64b382_idx',
        ),
        migrations.RenameField(
            model_name='miniofile',
            old_name='source_filename',
            new_name='key',
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['key'], name='files_stora_key_a2d65d_idx'),
        ),
    ]
