# Generated by Django 5.0.3 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files_storage", "0002_alter_filelocation_basename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filelocation",
            name="basename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Basename"
            ),
        ),
    ]
