# Generated by Django 3.2.12 on 2022-12-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0002_auto_20221229_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='miniofile',
            name='files_stora_updated_a6297c_idx',
        ),
        migrations.RemoveIndex(
            model_name='miniofile',
            name='files_stora_key_a2d65d_idx',
        ),
        migrations.RemoveField(
            model_name='miniofile',
            name='key',
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['created'], name='files_stora_created_964deb_idx'),
        ),
        migrations.AddField(
            model_name='fileversions',
            name='versions',
            field=models.ManyToManyField(to='files_storage.MinioFile'),
        ),
        migrations.AddIndex(
            model_name='fileversions',
            index=models.Index(fields=['key'], name='files_stora_key_691856_idx'),
        ),
    ]
