# Generated by Django 3.2.12 on 2022-12-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0003_auto_20221231_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileversions',
            name='versions',
        ),
    ]
