# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files_storage", "0004_remove_minioconfiguration_bucket_app_subdir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minioconfiguration",
            name="public_base_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Public base URL",
            ),
        ),
        migrations.AddField(
            model_name="minioconfiguration",
            name="write_prefix",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Write prefix",
            ),
        ),
        migrations.AlterField(
            model_name="filelocation",
            name="uri",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="URI"),
        ),
    ]
