# Generated by Django 3.2.12 on 2022-12-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_provider', '0005_auto_20221231_2043'),
        ('collection', '0008_auto_20221231_2043'),
        ('files_storage', '0004_remove_fileversions_versions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileVersions',
        ),
    ]
