from django.utils.translation import gettext_lazy as _


PUBLICATION_STATUS_WAITING_FOR_QA = 'WAITING_FOR_QA'
PUBLICATION_STATUS_QA = 'QA'
PUBLICATION_STATUS_SCHEDULED_TO_PUBLISH = 'SCHEDULED_TO_PUBLISH'
PUBLICATION_STATUS_PUBLISHED = 'PUBLISHED'


PUBLICATION_STATUS = (
    (PUBLICATION_STATUS_WAITING_FOR_QA, _('WAITING_FOR_QA')),
    (PUBLICATION_STATUS_QA, _('QA')),
    (PUBLICATION_STATUS_SCHEDULED_TO_PUBLISH, _('SCHEDULED_TO_PUBLISH')),
    (PUBLICATION_STATUS_PUBLISHED, _('PUBLISHED')),
)
