# Generated by Django 4.2.6 on 2024-02-07 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doi", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="XMLCrossRef",
        ),
    ]
