# Generated by Django 3.2.12 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doiwithlang',
            name='doi',
            field=models.TextField(verbose_name='DOI'),
        ),
    ]
