# Generated by Django 5.0.8 on 2025-08-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_alter_collection_acron_alter_collection_name_and_more"),
        ("doi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doiwithlang",
            name="doi",
            field=models.CharField(max_length=256, verbose_name="DOI"),
        ),
        migrations.AlterField(
            model_name="doiwithlang",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.language",
            ),
        ),
    ]
