# Generated by Django 5.2.3 on 2026-03-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_options_article_first_pubdate_iso'),
        ('doi', '0002_alter_doiwithlang_doi_alter_doiwithlang_lang'),
        ('journal', '0014_alter_journal_title_alter_officialjournal_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossrefConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('crossmark_policy_url', models.URLField(blank=True, help_text="URL of the journal's crossmark policy page", null=True, verbose_name='Crossmark Policy URL')),
                ('crossmark_policy_doi', models.CharField(blank=True, help_text="DOI of the journal's crossmark policy", max_length=256, null=True, verbose_name='Crossmark Policy DOI')),
                ('depositor_name', models.CharField(help_text='Name of the depositor (contact person or organization)', max_length=256, verbose_name='Depositor Name')),
                ('depositor_email', models.EmailField(help_text='Email address for deposit notifications', max_length=254, verbose_name='Depositor Email')),
                ('registrant', models.CharField(help_text='Name of the organization registering the DOIs (typically the publisher)', max_length=256, verbose_name='Registrant')),
                ('login_id', models.CharField(blank=True, help_text='Crossref member account username for API deposit', max_length=256, null=True, verbose_name='Crossref Login ID')),
                ('login_password', models.CharField(blank=True, help_text='Crossref member account password for API deposit', max_length=256, null=True, verbose_name='Crossref Login Password')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crossref_configuration', to='journal.journal', verbose_name='Journal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'Crossref Configuration',
                'verbose_name_plural': 'Crossref Configurations',
            },
        ),
        migrations.CreateModel(
            name='CrossrefDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=16, verbose_name='Status')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP Response Status')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Response Body')),
                ('batch_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Batch ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossref_deposits', to='article.article', verbose_name='Article')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('xml_crossref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='doi.xmlcrossref', verbose_name='Crossref XML')),
            ],
            options={
                'verbose_name': 'Crossref Deposit',
                'verbose_name_plural': 'Crossref Deposits',
                'ordering': ['-updated'],
            },
        ),
    ]
