# Generated by Django 3.2.19 on 2023-06-14 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doi', '0002_alter_doiwithlang_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLCrossRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('uri', models.URLField(blank=True, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='xmlcrossref_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xmlcrossref_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'XMLCrossRef',
                'verbose_name_plural': 'XMLCrossRef',
                'ordering': ('file',),
            },
        ),
    ]
