# Generated by Django 3.2.19 on 2023-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doi', '0003_xmlcrossref'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcrossref',
            name='pid',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
