# Generated by Django 4.2.6 on 2024-01-23 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnexpectedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "exception_type",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Type"
                    ),
                ),
                (
                    "exception_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Msg"
                    ),
                ),
                ("traceback", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exception_type"], name="tracker_une_excepti_47ede4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ERROR", "error"),
                            ("WARNING", "warning"),
                            ("INFO", "info"),
                            ("EXCEPTION", "exception"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Message type",
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "unexpected_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.unexpectedevent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message_type"], name="tracker_eve_message_34a6c9_idx"
                    )
                ],
            },
        ),
    ]
