# Generated by Django 5.0.3 on 2025-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="event",
            name="unexpected_event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="unexpectedevent",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="unexpectedevent",
            name="action",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Action"
            ),
        ),
        migrations.AddField(
            model_name="unexpectedevent",
            name="item",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Item"
            ),
        ),
        migrations.AddIndex(
            model_name="unexpectedevent",
            index=models.Index(fields=["item"], name="tracker_une_item_795336_idx"),
        ),
        migrations.AddIndex(
            model_name="unexpectedevent",
            index=models.Index(fields=["action"], name="tracker_une_action_55cd4b_idx"),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
