# Generated by Django 5.0.8 on 2025-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_remove_event_creator_remove_event_unexpected_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("started", "started"),
                            ("interrupted", "interrupted"),
                            ("finished", "finished"),
                        ],
                        default="started",
                        max_length=11,
                        null=True,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "indexes": [
                    models.Index(fields=["name"], name="tracker_tas_name_4ae960_idx"),
                    models.Index(
                        fields=["status"], name="tracker_tas_status_4e9707_idx"
                    ),
                ],
            },
        ),
    ]
