# Generated by Django 5.2.3 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_tasktracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktracker",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
