# Generated by Django 5.2.3 on 2025-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_tasktracker_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktracker",
            name="item",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Item"
            ),
        ),
    ]
