# Generated by Django 5.2.3 on 2025-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_tasktracker_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktracker",
            name="total_processed",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Total processed"
            ),
        ),
        migrations.AddField(
            model_name="tasktracker",
            name="total_to_process",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Total to process"
            ),
        ),
        migrations.AlterField(
            model_name="tasktracker",
            name="completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
